//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_monitor_log
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public short status { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string pin { get; set; }
        public string card_no { get; set; }
        public Nullable<int> device_id { get; set; }
        public string device_sn { get; set; }
        public string device_name { get; set; }
        public Nullable<int> verified { get; set; }
        public Nullable<int> state { get; set; }
        public string state_name { get; set; }
        public Nullable<short> event_type { get; set; }
        public Nullable<short> trigger_opt { get; set; }
        public Nullable<short> event_point_type { get; set; }
        public Nullable<int> event_point_id { get; set; }
        public string event_point_name { get; set; }
        public string description { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string dept { get; set; }
        public string area { get; set; }
    }
}
