//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class API
    {
        public API()
        {
            this.APIRolePermissions = new HashSet<APIRolePermission>();
            this.APIUserPermissions = new HashSet<APIUserPermission>();
        }
    
        public int APIId { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public int HttpVerbId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual HttpVerb HttpVerb { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<APIRolePermission> APIRolePermissions { get; set; }
        public virtual ICollection<APIUserPermission> APIUserPermissions { get; set; }
    }
}
