//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppraisalCycle
    {
        public AppraisalCycle()
        {
            this.AppraisalSettings = new HashSet<AppraisalSetting>();
            this.UserAchievementForMidYears = new HashSet<UserAchievementForMidYear>();
            this.UserDetails = new HashSet<UserDetail>();
            this.UserGoals = new HashSet<UserGoal>();
            this.TeamGoals = new HashSet<TeamGoal>();
        }
    
        public int AppraisalCycleId { get; set; }
        public int CountryId { get; set; }
        public int AppraisalMonth { get; set; }
        public int AppraisalYear { get; set; }
        public string AppraisalCycleName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<AppraisalSetting> AppraisalSettings { get; set; }
        public virtual ICollection<UserAchievementForMidYear> UserAchievementForMidYears { get; set; }
        public virtual ICollection<UserDetail> UserDetails { get; set; }
        public virtual ICollection<UserGoal> UserGoals { get; set; }
        public virtual ICollection<TeamGoal> TeamGoals { get; set; }
    }
}
