//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppraisalSetting
    {
        public AppraisalSetting()
        {
            this.AppraisalSettingDesignations = new HashSet<AppraisalSettingDesignation>();
            this.AppraisalSettingStages = new HashSet<AppraisalSettingStage>();
            this.EmpAppraisalSettings = new HashSet<EmpAppraisalSetting>();
            this.EmpAppraisalSettingLogs = new HashSet<EmpAppraisalSettingLog>();
        }
    
        public int AppraisalSettingId { get; set; }
        public int AppraisalCycleId { get; set; }
        public int LocationId { get; set; }
        public int VerticalId { get; set; }
        public int DivisionId { get; set; }
        public int DepartmentId { get; set; }
        public long TeamId { get; set; }
        public string DesignationIds { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual AppraisalCycle AppraisalCycle { get; set; }
        public virtual Department Department { get; set; }
        public virtual Division Division { get; set; }
        public virtual Location Location { get; set; }
        public virtual Team Team { get; set; }
        public virtual Vertical Vertical { get; set; }
        public virtual ICollection<AppraisalSettingDesignation> AppraisalSettingDesignations { get; set; }
        public virtual ICollection<AppraisalSettingStage> AppraisalSettingStages { get; set; }
        public virtual ICollection<EmpAppraisalSetting> EmpAppraisalSettings { get; set; }
        public virtual ICollection<EmpAppraisalSettingLog> EmpAppraisalSettingLogs { get; set; }
    }
}
