//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppraisalRating
    {
        public AppraisalRating()
        {
            this.EmpAppraisalParameterDetails = new HashSet<EmpAppraisalParameterDetail>();
            this.EmpAppraisalParameterDetails1 = new HashSet<EmpAppraisalParameterDetail>();
            this.EmpAppraisalParameterDetails2 = new HashSet<EmpAppraisalParameterDetail>();
        }
    
        public int AppraisalRatingId { get; set; }
        public int Rating { get; set; }
        public string RatingTitle { get; set; }
        public string RatingDescription { get; set; }
        public int Sequence { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual ICollection<EmpAppraisalParameterDetail> EmpAppraisalParameterDetails { get; set; }
        public virtual ICollection<EmpAppraisalParameterDetail> EmpAppraisalParameterDetails1 { get; set; }
        public virtual ICollection<EmpAppraisalParameterDetail> EmpAppraisalParameterDetails2 { get; set; }
    }
}
