//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetDetail
    {
        public AssetDetail()
        {
            this.AssetDetailAttributes = new HashSet<AssetDetailAttribute>();
            this.AssetTransactions = new HashSet<AssetTransaction>();
        }
    
        public long AssetDetailId { get; set; }
        public Nullable<long> AssetId { get; set; }
        public string SerialNo { get; set; }
        public string AssetTag { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual ICollection<AssetDetailAttribute> AssetDetailAttributes { get; set; }
        public virtual ICollection<AssetTransaction> AssetTransactions { get; set; }
        public virtual User User { get; set; }
    }
}
