//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetType
    {
        public AssetType()
        {
            this.Assets = new HashSet<Asset>();
            this.AssetRequests = new HashSet<AssetRequest>();
            this.AssetsMasters = new HashSet<AssetsMaster>();
            this.DepartmentWiseAssetLimits = new HashSet<DepartmentWiseAssetLimit>();
        }
    
        public long TypeId { get; set; }
        public string Type { get; set; }
        public bool IsForTemporaryBasis { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual ICollection<AssetRequest> AssetRequests { get; set; }
        public virtual ICollection<AssetsMaster> AssetsMasters { get; set; }
        public virtual ICollection<DepartmentWiseAssetLimit> DepartmentWiseAssetLimits { get; set; }
        public virtual User User { get; set; }
    }
}
