//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDataChangeRequestApplication
    {
        public AttendanceDataChangeRequestApplication()
        {
            this.AttendanceDataChangeRequestHistories = new HashSet<AttendanceDataChangeRequestHistory>();
        }
    
        public long RequestId { get; set; }
        public long RequestApplicationId { get; set; }
        public int RequestCategoryid { get; set; }
        public string Reason { get; set; }
        public long StatusId { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public string ApproverRemarks { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<bool> LastModifiedBy { get; set; }
    
        public virtual AttendanceDataChangeRequestCategory AttendanceDataChangeRequestCategory { get; set; }
        public virtual ICollection<AttendanceDataChangeRequestHistory> AttendanceDataChangeRequestHistories { get; set; }
    }
}
