//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDataChangeRequestHistory
    {
        public long RecordId { get; set; }
        public long RequestId { get; set; }
        public long StatusId { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public string ApproverRemarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual AttendanceDataChangeRequestApplication AttendanceDataChangeRequestApplication { get; set; }
    }
}
