//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabRequest
    {
        public CabRequest()
        {
            this.CabRequestHistories = new HashSet<CabRequestHistory>();
        }
    
        public long CabRequestId { get; set; }
        public int UserId { get; set; }
        public long DateId { get; set; }
        public string EmpContactNo { get; set; }
        public int CabShiftId { get; set; }
        public int CabPDLocationId { get; set; }
        public string LocationDetail { get; set; }
        public int StatusId { get; set; }
        public Nullable<long> ApproverId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual CabPickDropLocation CabPickDropLocation { get; set; }
        public virtual CabStatusMaster CabStatusMaster { get; set; }
        public virtual DateMaster DateMaster { get; set; }
        public virtual CabShiftMaster CabShiftMaster { get; set; }
        public virtual ICollection<CabRequestHistory> CabRequestHistories { get; set; }
        public virtual User User { get; set; }
    }
}
