//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabStatusMaster
    {
        public CabStatusMaster()
        {
            this.CabRequests = new HashSet<CabRequest>();
            this.CabRequestHistories = new HashSet<CabRequestHistory>();
        }
    
        public int StatusId { get; set; }
        public string StatusCode { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual ICollection<CabRequest> CabRequests { get; set; }
        public virtual ICollection<CabRequestHistory> CabRequestHistories { get; set; }
    }
}
