//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabShiftMaster
    {
        public CabShiftMaster()
        {
            this.CabRequests = new HashSet<CabRequest>();
        }
    
        public int CabShiftId { get; set; }
        public int ServiceTypeId { get; set; }
        public string CabShiftName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual ICollection<CabRequest> CabRequests { get; set; }
    }
}
