//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeExtnRequest
    {
        public int RequestId { get; set; }
        public string NewMobileNo { get; set; }
        public string NewExtnNo { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsActionPerformed { get; set; }
        public string Reason { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedById { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<int> ActionTakenById { get; set; }
        public string NewImage { get; set; }
        public string OldMobileNo { get; set; }
        public string OldImage { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
