//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientResourceMaster
    {
        public long ClientResourceId { get; set; }
        public string ResourceName { get; set; }
        public long ClientId { get; set; }
        public string ClientProjectName { get; set; }
        public string ClientProjectCode { get; set; }
        public string ClientProjectDescription { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public string FriendlyName { get; set; }
    
        public virtual ClientMaster ClientMaster { get; set; }
        public virtual User User { get; set; }
    }
}
