//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMaster
    {
        public ClientMaster()
        {
            this.ClientResourceMasters = new HashSet<ClientResourceMaster>();
            this.ClientSideManagerMasters = new HashSet<ClientSideManagerMaster>();
            this.ProjectMasters = new HashSet<ProjectMaster>();
        }
    
        public long ClientId { get; set; }
        public string ClientName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual ICollection<ClientResourceMaster> ClientResourceMasters { get; set; }
        public virtual ICollection<ClientSideManagerMaster> ClientSideManagerMasters { get; set; }
        public virtual ICollection<ProjectMaster> ProjectMasters { get; set; }
    }
}
