//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetencyType
    {
        public CompetencyType()
        {
            this.AppraisalParameters = new HashSet<AppraisalParameter>();
            this.CompetencyFormDetails = new HashSet<CompetencyFormDetail>();
        }
    
        public int CompetencyTypeId { get; set; }
        public string CompetencyTypeName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual ICollection<AppraisalParameter> AppraisalParameters { get; set; }
        public virtual ICollection<CompetencyFormDetail> CompetencyFormDetails { get; set; }
    }
}
