//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetencyFormDetail
    {
        public CompetencyFormDetail()
        {
            this.EmpAppraisalParameterDetails = new HashSet<EmpAppraisalParameterDetail>();
        }
    
        public int CompetencyFormDetailId { get; set; }
        public int CompetencyFormId { get; set; }
        public int CompetencyTypeId { get; set; }
        public int ParameterId { get; set; }
        public string EvaluationCriteria { get; set; }
        public bool IsRating { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual AppraisalParameter AppraisalParameter { get; set; }
        public virtual CompetencyForm CompetencyForm { get; set; }
        public virtual CompetencyType CompetencyType { get; set; }
        public virtual ICollection<EmpAppraisalParameterDetail> EmpAppraisalParameterDetails { get; set; }
    }
}
