//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetencyForm
    {
        public CompetencyForm()
        {
            this.CompetencyFormDetails = new HashSet<CompetencyFormDetail>();
            this.EmpAppraisalSettings = new HashSet<EmpAppraisalSetting>();
            this.EmpAppraisalSettingLogs = new HashSet<EmpAppraisalSettingLog>();
        }
    
        public int CompetencyFormId { get; set; }
        public string CompetencyFormName { get; set; }
        public string SpecializedFormName { get; set; }
        public int LocationId { get; set; }
        public int VerticalId { get; set; }
        public int DivisionId { get; set; }
        public int DepartmentId { get; set; }
        public int DesignationId { get; set; }
        public int FeedbackTypeId { get; set; }
        public bool IsRating { get; set; }
        public bool IsFinalized { get; set; }
        public Nullable<System.DateTime> FinalizedDate { get; set; }
        public Nullable<bool> IsRetired { get; set; }
        public Nullable<System.DateTime> RetiredDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual Division Division { get; set; }
        public virtual FeedbackType FeedbackType { get; set; }
        public virtual Location Location { get; set; }
        public virtual Vertical Vertical { get; set; }
        public virtual ICollection<CompetencyFormDetail> CompetencyFormDetails { get; set; }
        public virtual ICollection<EmpAppraisalSetting> EmpAppraisalSettings { get; set; }
        public virtual ICollection<EmpAppraisalSettingLog> EmpAppraisalSettingLogs { get; set; }
    }
}
