//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateMaster
    {
        public DateMaster()
        {
            this.AssetTransactions = new HashSet<AssetTransaction>();
            this.AssetTransactions1 = new HashSet<AssetTransaction>();
            this.AssetTransactions2 = new HashSet<AssetTransaction>();
            this.CardPunchinDatas = new HashSet<CardPunchinData>();
            this.EmployeeWiseWeekOffs = new HashSet<EmployeeWiseWeekOff>();
            this.TempUserShiftDetails = new HashSet<TempUserShiftDetail>();
            this.DateWiseAttendances = new HashSet<DateWiseAttendance>();
            this.DateWiseAttendanceAsquares = new HashSet<DateWiseAttendanceAsquare>();
            this.DateWiseLeaveTypes = new HashSet<DateWiseLeaveType>();
            this.DateWiseLNSAs = new HashSet<DateWiseLNSA>();
            this.DateWisePunchInDatas = new HashSet<DateWisePunchInData>();
            this.LeaveRequestApplications = new HashSet<LeaveRequestApplication>();
            this.LeaveRequestApplications1 = new HashSet<LeaveRequestApplication>();
            this.LegitimateLeaveRequests = new HashSet<LegitimateLeaveRequest>();
            this.LegitimateLeaveRequestHistories = new HashSet<LegitimateLeaveRequestHistory>();
            this.ListofHolidays = new HashSet<ListofHoliday>();
            this.OutingRequests = new HashSet<OutingRequest>();
            this.OutingRequests1 = new HashSet<OutingRequest>();
            this.RequestCompOffs = new HashSet<RequestCompOff>();
            this.RequestLnsas = new HashSet<RequestLnsa>();
            this.RequestLnsas1 = new HashSet<RequestLnsa>();
            this.CabRequests = new HashSet<CabRequest>();
            this.UserGoals = new HashSet<UserGoal>();
            this.UserGoals1 = new HashSet<UserGoal>();
            this.UserGoalHistories = new HashSet<UserGoalHistory>();
            this.UserGoalHistories1 = new HashSet<UserGoalHistory>();
            this.TeamGoals = new HashSet<TeamGoal>();
            this.TeamGoals1 = new HashSet<TeamGoal>();
            this.TeamGoalHistories = new HashSet<TeamGoalHistory>();
            this.TeamGoalHistories1 = new HashSet<TeamGoalHistory>();
        }
    
        public long DateId { get; set; }
        public System.DateTime Date { get; set; }
        public string Day { get; set; }
        public bool IsWeekend { get; set; }
    
        public virtual ICollection<AssetTransaction> AssetTransactions { get; set; }
        public virtual ICollection<AssetTransaction> AssetTransactions1 { get; set; }
        public virtual ICollection<AssetTransaction> AssetTransactions2 { get; set; }
        public virtual ICollection<CardPunchinData> CardPunchinDatas { get; set; }
        public virtual ICollection<EmployeeWiseWeekOff> EmployeeWiseWeekOffs { get; set; }
        public virtual ICollection<TempUserShiftDetail> TempUserShiftDetails { get; set; }
        public virtual ICollection<DateWiseAttendance> DateWiseAttendances { get; set; }
        public virtual ICollection<DateWiseAttendanceAsquare> DateWiseAttendanceAsquares { get; set; }
        public virtual ICollection<DateWiseLeaveType> DateWiseLeaveTypes { get; set; }
        public virtual ICollection<DateWiseLNSA> DateWiseLNSAs { get; set; }
        public virtual ICollection<DateWisePunchInData> DateWisePunchInDatas { get; set; }
        public virtual ICollection<LeaveRequestApplication> LeaveRequestApplications { get; set; }
        public virtual ICollection<LeaveRequestApplication> LeaveRequestApplications1 { get; set; }
        public virtual ICollection<LegitimateLeaveRequest> LegitimateLeaveRequests { get; set; }
        public virtual ICollection<LegitimateLeaveRequestHistory> LegitimateLeaveRequestHistories { get; set; }
        public virtual ICollection<ListofHoliday> ListofHolidays { get; set; }
        public virtual ICollection<OutingRequest> OutingRequests { get; set; }
        public virtual ICollection<OutingRequest> OutingRequests1 { get; set; }
        public virtual ICollection<RequestCompOff> RequestCompOffs { get; set; }
        public virtual ICollection<RequestLnsa> RequestLnsas { get; set; }
        public virtual ICollection<RequestLnsa> RequestLnsas1 { get; set; }
        public virtual ICollection<CabRequest> CabRequests { get; set; }
        public virtual ICollection<UserGoal> UserGoals { get; set; }
        public virtual ICollection<UserGoal> UserGoals1 { get; set; }
        public virtual ICollection<UserGoalHistory> UserGoalHistories { get; set; }
        public virtual ICollection<UserGoalHistory> UserGoalHistories1 { get; set; }
        public virtual ICollection<TeamGoal> TeamGoals { get; set; }
        public virtual ICollection<TeamGoal> TeamGoals1 { get; set; }
        public virtual ICollection<TeamGoalHistory> TeamGoalHistories { get; set; }
        public virtual ICollection<TeamGoalHistory> TeamGoalHistories1 { get; set; }
    }
}
