//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.AppraisalSettings = new HashSet<AppraisalSetting>();
            this.CompetencyForms = new HashSet<CompetencyForm>();
            this.DepartmentWiseAssetLimits = new HashSet<DepartmentWiseAssetLimit>();
            this.EmpAppraisalSettings = new HashSet<EmpAppraisalSetting>();
            this.EmpAppraisalSettingLogs = new HashSet<EmpAppraisalSettingLog>();
            this.Forms = new HashSet<Form>();
            this.Teams = new HashSet<Team>();
        }
    
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string Description { get; set; }
        public int DepartmentHeadId { get; set; }
        public int DivisionId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual ICollection<AppraisalSetting> AppraisalSettings { get; set; }
        public virtual ICollection<CompetencyForm> CompetencyForms { get; set; }
        public virtual Division Division { get; set; }
        public virtual ICollection<DepartmentWiseAssetLimit> DepartmentWiseAssetLimits { get; set; }
        public virtual ICollection<EmpAppraisalSetting> EmpAppraisalSettings { get; set; }
        public virtual ICollection<EmpAppraisalSettingLog> EmpAppraisalSettingLogs { get; set; }
        public virtual ICollection<Form> Forms { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual User User { get; set; }
    }
}
