//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        public Designation()
        {
            this.AppraisalSettingDesignations = new HashSet<AppraisalSettingDesignation>();
            this.CompetencyForms = new HashSet<CompetencyForm>();
            this.EmpAppraisalSettings = new HashSet<EmpAppraisalSetting>();
            this.EmpAppraisalSettingLogs = new HashSet<EmpAppraisalSettingLog>();
            this.UserDetails = new HashSet<UserDetail>();
        }
    
        public int DesignationId { get; set; }
        public string DesignationName { get; set; }
        public bool IsIntern { get; set; }
        public int DesignationGroupId { get; set; }
        public Nullable<int> SpecialDesignationGropupId { get; set; }
        public int Sequence { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual ICollection<AppraisalSettingDesignation> AppraisalSettingDesignations { get; set; }
        public virtual ICollection<CompetencyForm> CompetencyForms { get; set; }
        public virtual DesignationGroup DesignationGroup { get; set; }
        public virtual DesignationGroup DesignationGroup1 { get; set; }
        public virtual ICollection<EmpAppraisalSetting> EmpAppraisalSettings { get; set; }
        public virtual ICollection<EmpAppraisalSettingLog> EmpAppraisalSettingLogs { get; set; }
        public virtual ICollection<UserDetail> UserDetails { get; set; }
    }
}
