//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentPermissionGroup
    {
        public DocumentPermissionGroup()
        {
            this.DocumentPermissionGroupPermissions = new HashSet<DocumentPermissionGroupPermission>();
            this.SharedGroupDocuments = new HashSet<SharedGroupDocument>();
        }
    
        public int DocumentPermissionGroupId { get; set; }
        public string Name { get; set; }
        public int CreatedByUserId { get; set; }
    
        public virtual ICollection<DocumentPermissionGroupPermission> DocumentPermissionGroupPermissions { get; set; }
        public virtual ICollection<SharedGroupDocument> SharedGroupDocuments { get; set; }
        public virtual User User { get; set; }
    }
}
