//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAppraisalLog
    {
        public int EmpAppraisalLogId { get; set; }
        public long EmpAppraisalSettingId { get; set; }
        public int AppraisalStatusId { get; set; }
        public string ActionDescription { get; set; }
        public string Comment { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
    
        public virtual EmpAppraisalSetting EmpAppraisalSetting { get; set; }
        public virtual FeedbackStatu FeedbackStatu { get; set; }
    }
}
