//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAppraisal
    {
        public EmpAppraisal()
        {
            this.EmpAppraisalParameterDetails = new HashSet<EmpAppraisalParameterDetail>();
        }
    
        public long EmpAppraisalId { get; set; }
        public long EmpAppraisalSettingId { get; set; }
        public Nullable<System.DateTime> ExposerFrom { get; set; }
        public Nullable<System.DateTime> ExposerTo { get; set; }
        public string AppraiseeComment { get; set; }
        public Nullable<System.DateTime> SelfSubmitDate { get; set; }
        public string AppraiserComment { get; set; }
        public Nullable<System.DateTime> AppraiserSubmitDate { get; set; }
        public string Approver1Comment { get; set; }
        public Nullable<System.DateTime> Approver1SubmitDate { get; set; }
        public string Approver2Comment { get; set; }
        public Nullable<System.DateTime> Approver2SubmitDate { get; set; }
        public string Approver3Comment { get; set; }
        public Nullable<System.DateTime> Approver3SubmitDate { get; set; }
        public Nullable<int> AppraiserRecommendedForDesignationId { get; set; }
        public Nullable<int> AppraiserRecommendedPercentage { get; set; }
        public string AppraiserRecommendationComment { get; set; }
        public Nullable<int> Approver1RecommendedForDesignationId { get; set; }
        public Nullable<int> Approver1RecommendedPercentage { get; set; }
        public string Approver1RecommendationComment { get; set; }
        public Nullable<bool> AppraiserMarkedHighPotential { get; set; }
        public string AppraiserHighPotentialComment { get; set; }
        public Nullable<bool> Approver1MarkedHighPotential { get; set; }
        public string Approver1HighPotentialComment { get; set; }
        public Nullable<int> PromotionDesignationId { get; set; }
        public Nullable<System.DateTime> PromotionDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public string SelfOverallRating { get; set; }
        public string AppraiserOverallRating { get; set; }
        public string ApproverOverallRating { get; set; }
        public string PromotionOverallRating { get; set; }
    
        public virtual EmpAppraisalSetting EmpAppraisalSetting { get; set; }
        public virtual ICollection<EmpAppraisalParameterDetail> EmpAppraisalParameterDetails { get; set; }
    }
}
