//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAppraisalSetting
    {
        public EmpAppraisalSetting()
        {
            this.EmpAppraisals = new HashSet<EmpAppraisal>();
            this.EmpAppraisalLogs = new HashSet<EmpAppraisalLog>();
            this.EmpAppraisalSettingLogs = new HashSet<EmpAppraisalSettingLog>();
            this.EmpAppraisalSettingStages = new HashSet<EmpAppraisalSettingStage>();
            this.UserAchievements = new HashSet<UserAchievement>();
        }
    
        public long EmpAppraisalSettingId { get; set; }
        public int AppraisalSettingId { get; set; }
        public int UserId { get; set; }
        public int LocationId { get; set; }
        public int VerticalId { get; set; }
        public int DivisionId { get; set; }
        public int DepartmentId { get; set; }
        public long TeamId { get; set; }
        public int DesignationId { get; set; }
        public Nullable<System.DateTime> LastPromotionDate { get; set; }
        public Nullable<int> LastPromotionDesignationId { get; set; }
        public Nullable<int> LastAppraisalCycleId { get; set; }
        public int CurrentAppraisalCycleId { get; set; }
        public int RMId { get; set; }
        public int AppraiserId { get; set; }
        public int Approver1 { get; set; }
        public Nullable<int> Approver2 { get; set; }
        public Nullable<int> Approver3 { get; set; }
        public Nullable<int> HRId { get; set; }
        public Nullable<int> CompetencyFormId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int AppraisalStatusId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual AppraisalSetting AppraisalSetting { get; set; }
        public virtual CompetencyForm CompetencyForm { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual Division Division { get; set; }
        public virtual ICollection<EmpAppraisal> EmpAppraisals { get; set; }
        public virtual ICollection<EmpAppraisalLog> EmpAppraisalLogs { get; set; }
        public virtual FeedbackStatu FeedbackStatu { get; set; }
        public virtual Location Location { get; set; }
        public virtual Team Team { get; set; }
        public virtual Vertical Vertical { get; set; }
        public virtual ICollection<EmpAppraisalSettingLog> EmpAppraisalSettingLogs { get; set; }
        public virtual ICollection<EmpAppraisalSettingStage> EmpAppraisalSettingStages { get; set; }
        public virtual ICollection<UserAchievement> UserAchievements { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
    }
}
