//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeProfile
    {
        public EmployeeProfile()
        {
            this.CertificationsAndRewards = new HashSet<CertificationsAndReward>();
            this.ProfessionalAndEducationalExperiences = new HashSet<ProfessionalAndEducationalExperience>();
        }
    
        public long ProfileId { get; set; }
        public int UserId { get; set; }
        public string About { get; set; }
        public string Skills { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual ICollection<CertificationsAndReward> CertificationsAndRewards { get; set; }
        public virtual ICollection<ProfessionalAndEducationalExperience> ProfessionalAndEducationalExperiences { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
