//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gender
    {
        public Gender()
        {
            this.UserFamilyDetails = new HashSet<UserFamilyDetail>();
            this.UserDetails = new HashSet<UserDetail>();
        }
    
        public int GenderId { get; set; }
        public string GenderType { get; set; }
    
        public virtual ICollection<UserFamilyDetail> UserFamilyDetails { get; set; }
        public virtual ICollection<UserDetail> UserDetails { get; set; }
    }
}
