//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalCategory
    {
        public GoalCategory()
        {
            this.UserGoals = new HashSet<UserGoal>();
            this.UserGoalHistories = new HashSet<UserGoalHistory>();
            this.TeamGoals = new HashSet<TeamGoal>();
            this.TeamGoalHistories = new HashSet<TeamGoalHistory>();
        }
    
        public int GoalCategoryId { get; set; }
        public string Category { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<UserGoal> UserGoals { get; set; }
        public virtual ICollection<UserGoalHistory> UserGoalHistories { get; set; }
        public virtual ICollection<TeamGoal> TeamGoals { get; set; }
        public virtual ICollection<TeamGoalHistory> TeamGoalHistories { get; set; }
    }
}
