//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSOCProjectSubscriber
    {
        public int GSOCProjectSubscriberId { get; set; }
        public int GSOCProjectId { get; set; }
        public int UserId { get; set; }
        public string ProjectTitle { get; set; }
        public string Brief { get; set; }
        public string ExpectedResult { get; set; }
        public string Solution { get; set; }
        public string TimelineDistribution { get; set; }
        public string FuturePlans { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public string FilePath { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual GSOCProject GSOCProject { get; set; }
        public virtual User User { get; set; }
    }
}
