//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRACalculation
    {
        public int HRACalculationId { get; set; }
        public Nullable<double> PercentPaidRentExceedOfBS { get; set; }
        public Nullable<double> PercentAmtOfBS { get; set; }
        public Nullable<double> PercentAmtOfGrossSalary { get; set; }
        public Nullable<int> FinancialYear { get; set; }
    }
}
