//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceRequest
    {
        public InvoiceRequest()
        {
            this.InvoiceRequestDetails = new HashSet<InvoiceRequestDetail>();
        }
    
        public long InvoiceRequestId { get; set; }
        public int UserId { get; set; }
        public bool IsApproved { get; set; }
        public bool IsRejected { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<InvoiceRequestDetail> InvoiceRequestDetails { get; set; }
        public virtual User User { get; set; }
    }
}
