//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApprovalLevelRole
    {
        public int LeaveApprovalLevelRoleId { get; set; }
        public int RoleId { get; set; }
        public int LeaveApprovalLevelId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual LeaveApprovalLevel LeaveApprovalLevel { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
