//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveTypeGeneralRule
    {
        public int GeneralRuleId { get; set; }
        public bool CanAdminManage { get; set; }
        public bool CanSupervisorManage { get; set; }
        public bool CanEmployeeApply { get; set; }
        public bool IsEnableAccrual { get; set; }
        public bool IsEnableCarryForward { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
    }
}
