//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveBalance
    {
        public LeaveBalance()
        {
            this.LeaveBalanceHistories = new HashSet<LeaveBalanceHistory>();
        }
    
        public long RecordId { get; set; }
        public int UserId { get; set; }
        public long LeaveTypeId { get; set; }
        public double Count { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public int AllocationFrequency { get; set; }
    
        public virtual LeaveTypeMaster LeaveTypeMaster { get; set; }
        public virtual ICollection<LeaveBalanceHistory> LeaveBalanceHistories { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
