//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveStatusMaster
    {
        public LeaveStatusMaster()
        {
            this.LeaveHistories = new HashSet<LeaveHistory>();
            this.RequestCompOffs = new HashSet<RequestCompOff>();
            this.RequestCompOffHistories = new HashSet<RequestCompOffHistory>();
            this.LeaveRequestApplications = new HashSet<LeaveRequestApplication>();
        }
    
        public long StatusId { get; set; }
        public string StatusCode { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual ICollection<LeaveHistory> LeaveHistories { get; set; }
        public virtual ICollection<RequestCompOff> RequestCompOffs { get; set; }
        public virtual ICollection<RequestCompOffHistory> RequestCompOffHistories { get; set; }
        public virtual ICollection<LeaveRequestApplication> LeaveRequestApplications { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
