//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApprovalLevel
    {
        public LeaveApprovalLevel()
        {
            this.LeaveApplications = new HashSet<LeaveApplication>();
            this.LeaveApplicationApprovalLabelAssts = new HashSet<LeaveApplicationApprovalLabelAsst>();
            this.LeaveApprovalLevelRoles = new HashSet<LeaveApprovalLevelRole>();
        }
    
        public int LeaveApprovalLevelId { get; set; }
        public int LevelNum { get; set; }
        public int LeaveTypeId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ICollection<LeaveApplication> LeaveApplications { get; set; }
        public virtual ICollection<LeaveApplicationApprovalLabelAsst> LeaveApplicationApprovalLabelAssts { get; set; }
        public virtual ICollection<LeaveApprovalLevelRole> LeaveApprovalLevelRoles { get; set; }
    }
}
