//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRequestApplicationDetail
    {
        public long LeaveRequestApplicationDetailId { get; set; }
        public long LeaveRequestApplicationId { get; set; }
        public long LeaveTypeId { get; set; }
        public double Count { get; set; }
    
        public virtual LeaveTypeMaster LeaveTypeMaster { get; set; }
        public virtual LeaveRequestApplication LeaveRequestApplication { get; set; }
    }
}
