//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApplicationApprovalLabelAsst
    {
        public int LeaveApplicationApprovalLabelAsstId { get; set; }
        public int LeaveApplicationId { get; set; }
        public int ApprovalLevelId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public int ApplicationStatusId { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public string ReplyRemark { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> CurrentApprovalLevel { get; set; }
        public Nullable<int> TotalApprovalLevel { get; set; }
    
        public virtual LeaveApplication LeaveApplication { get; set; }
        public virtual LeaveApplicationStatu LeaveApplicationStatu { get; set; }
        public virtual LeaveApprovalLevel LeaveApprovalLevel { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
