//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApplicationStatu
    {
        public LeaveApplicationStatu()
        {
            this.LeaveApplications = new HashSet<LeaveApplication>();
            this.LeaveApplications1 = new HashSet<LeaveApplication>();
            this.LeaveApplicationApprovalLabelAssts = new HashSet<LeaveApplicationApprovalLabelAsst>();
        }
    
        public int LeaveApplicationStatusId { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<LeaveApplication> LeaveApplications { get; set; }
        public virtual ICollection<LeaveApplication> LeaveApplications1 { get; set; }
        public virtual ICollection<LeaveApplicationApprovalLabelAsst> LeaveApplicationApprovalLabelAssts { get; set; }
    }
}
