//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveTypeRestriction
    {
        public int ApplyRestrictionId { get; set; }
        public bool IsNotAllowedMoreThanLeaveBalance { get; set; }
        public bool IsNotAllowedPartialLeave { get; set; }
        public Nullable<int> MinServicePeriodRequired { get; set; }
        public Nullable<int> MaxConsecutiveLeave { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
    }
}
