//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveTypeCarryForwardRule
    {
        public int CarryForwardRuleId { get; set; }
        public Nullable<int> TakeLeaveWithinMonths { get; set; }
        public Nullable<int> MaxLeaveToCarryForward { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
    
        public virtual LeaveTypeCarryForwardRule LeaveTypeCarryForwardRule1 { get; set; }
        public virtual LeaveTypeCarryForwardRule LeaveTypeCarryForwardRule2 { get; set; }
    }
}
