//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApprovalLabelEmpAsst
    {
        public int ApprovalLabelEmpAsstId { get; set; }
        public int ApprovalLabelId { get; set; }
        public int EmpId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int UserId { get; set; }
    
        public virtual LeaveApprovalLabel LeaveApprovalLabel { get; set; }
        public virtual User User { get; set; }
    }
}
