//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApplication
    {
        public LeaveApplication()
        {
            this.LeaveApplicationApprovalLabelAssts = new HashSet<LeaveApplicationApprovalLabelAsst>();
        }
    
        public int LeaveApplicationId { get; set; }
        public int LeaveTypeId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<double> WorkingDayLeave { get; set; }
        public Nullable<int> ApprovingOfficerId { get; set; }
        public string AddressWhileOnLeave { get; set; }
        public string ContactNoWhileOnLeave { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public string ReplyRemark { get; set; }
        public Nullable<double> PendingLeave { get; set; }
        public Nullable<double> SpecificLeave { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> IsFromDateHalfDay { get; set; }
        public Nullable<bool> IsToDateHalfDay { get; set; }
        public Nullable<int> CurrentApprovalLevel { get; set; }
        public Nullable<int> TotalApprovalLevel { get; set; }
        public Nullable<int> LeaveApprovalLevelId { get; set; }
    
        public virtual ICollection<LeaveApplicationApprovalLabelAsst> LeaveApplicationApprovalLabelAssts { get; set; }
        public virtual LeaveApplicationStatu LeaveApplicationStatu { get; set; }
        public virtual User User { get; set; }
        public virtual LeaveApplicationStatu LeaveApplicationStatu1 { get; set; }
        public virtual LeaveApprovalLevel LeaveApprovalLevel { get; set; }
    }
}
