//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRequestApplication
    {
        public LeaveRequestApplication()
        {
            this.DateWiseLeaveTypes = new HashSet<DateWiseLeaveType>();
            this.LeaveHistories = new HashSet<LeaveHistory>();
            this.LeaveRequestApplicationDetails = new HashSet<LeaveRequestApplicationDetail>();
            this.LegitimateLeaveRequests = new HashSet<LegitimateLeaveRequest>();
            this.RequestCompOffDetails = new HashSet<RequestCompOffDetail>();
            this.AdvanceLeaveDetails = new HashSet<AdvanceLeaveDetail>();
        }
    
        public long LeaveRequestApplicationId { get; set; }
        public int UserId { get; set; }
        public long FromDateId { get; set; }
        public long TillDateId { get; set; }
        public double NoOfTotalDays { get; set; }
        public double NoOfWorkingDays { get; set; }
        public string Reason { get; set; }
        public string PrimaryContactNo { get; set; }
        public string AlternativeContactNo { get; set; }
        public bool IsAvailableOnMobile { get; set; }
        public bool IsAvailableOnEmail { get; set; }
        public long StatusId { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public string ApproverRemarks { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public string LeaveCombination { get; set; }
    
        public virtual ICollection<DateWiseLeaveType> DateWiseLeaveTypes { get; set; }
        public virtual ICollection<LeaveHistory> LeaveHistories { get; set; }
        public virtual LeaveStatusMaster LeaveStatusMaster { get; set; }
        public virtual ICollection<LeaveRequestApplicationDetail> LeaveRequestApplicationDetails { get; set; }
        public virtual ICollection<LegitimateLeaveRequest> LegitimateLeaveRequests { get; set; }
        public virtual ICollection<RequestCompOffDetail> RequestCompOffDetails { get; set; }
        public virtual DateMaster DateMaster { get; set; }
        public virtual DateMaster DateMaster1 { get; set; }
        public virtual ICollection<AdvanceLeaveDetail> AdvanceLeaveDetails { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
    }
}
