//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LNSAStatusMaster
    {
        public LNSAStatusMaster()
        {
            this.RequestLnsaHistories = new HashSet<RequestLnsaHistory>();
            this.RequestLnsas = new HashSet<RequestLnsa>();
            this.DateWiseLNSAs = new HashSet<DateWiseLNSA>();
        }
    
        public long StatusId { get; set; }
        public string Status { get; set; }
        public string StatusCode { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual ICollection<RequestLnsaHistory> RequestLnsaHistories { get; set; }
        public virtual ICollection<RequestLnsa> RequestLnsas { get; set; }
        public virtual ICollection<DateWiseLNSA> DateWiseLNSAs { get; set; }
    }
}
