//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.AppraisalSettings = new HashSet<AppraisalSetting>();
            this.CompetencyForms = new HashSet<CompetencyForm>();
            this.EmpAppraisalSettings = new HashSet<EmpAppraisalSetting>();
            this.EmpAppraisalSettingLogs = new HashSet<EmpAppraisalSettingLog>();
            this.CabPickDropLocations = new HashSet<CabPickDropLocation>();
            this.SupportingStaffMembers = new HashSet<SupportingStaffMember>();
            this.VehicleDetails = new HashSet<VehicleDetail>();
            this.Users = new HashSet<User>();
        }
    
        public int LocationId { get; set; }
        public string LocationName { get; set; }
        public int CompanyId { get; set; }
        public int CityId { get; set; }
        public int StateId { get; set; }
        public int CountryId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<AppraisalSetting> AppraisalSettings { get; set; }
        public virtual City City { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<CompetencyForm> CompetencyForms { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<EmpAppraisalSetting> EmpAppraisalSettings { get; set; }
        public virtual ICollection<EmpAppraisalSettingLog> EmpAppraisalSettingLogs { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<CabPickDropLocation> CabPickDropLocations { get; set; }
        public virtual ICollection<SupportingStaffMember> SupportingStaffMembers { get; set; }
        public virtual ICollection<VehicleDetail> VehicleDetails { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
