//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManpowerRequisitionForm
    {
        public long ManpowerRequisitionFormDataId { get; set; }
        public long InviteId { get; set; }
        public string FormSubmittedTo { get; set; }
        public string Department { get; set; }
        public Nullable<bool> IsReplacement { get; set; }
        public string ReplacedEmployeeName { get; set; }
        public string ReplacedEmployeeDesignation { get; set; }
        public Nullable<bool> IsPlacementNew { get; set; }
        public Nullable<long> NumberOfNewPlacement { get; set; }
        public string FixedCTC { get; set; }
        public string GrossBudget { get; set; }
        public string JobRequirement { get; set; }
        public System.DateTime ETAofClosingHiring { get; set; }
        public System.DateTime ETAofJoining { get; set; }
        public string EducationalQualification { get; set; }
        public string JobDescription { get; set; }
        public long MinExperienceRequired { get; set; }
        public long MaxExperienceRequired { get; set; }
        public string SpecialSkillRequirement { get; set; }
        public string SupervisorName { get; set; }
        public string SupervisorDesignation { get; set; }
        public string TechnologyRequired { get; set; }
        public string TechnologyLevelRequired { get; set; }
        public int Version { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ManpowerRequisitionInvite ManpowerRequisitionInvite { get; set; }
    }
}
