//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealPackageFeedback
    {
        public int MealPackageFeedbackId { get; set; }
        public int MealPackageId { get; set; }
        public bool Liked { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
    
        public virtual MealPackage MealPackage { get; set; }
        public virtual User User { get; set; }
    }
}
