//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealPackage
    {
        public MealPackage()
        {
            this.MealPackageDetails = new HashSet<MealPackageDetail>();
            this.MealPackageFeedbacks = new HashSet<MealPackageFeedback>();
        }
    
        public int MealPackageId { get; set; }
        public string MealPackageName { get; set; }
        public int MealPeriodId { get; set; }
        public int MealTypeId { get; set; }
        public int MealCategoryId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual MealCategory MealCategory { get; set; }
        public virtual MealPeriod MealPeriod { get; set; }
        public virtual MealType MealType { get; set; }
        public virtual ICollection<MealPackageDetail> MealPackageDetails { get; set; }
        public virtual ICollection<MealPackageFeedback> MealPackageFeedbacks { get; set; }
    }
}
