//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealPackageDetail
    {
        public long MealPackageDetailId { get; set; }
        public int MealPackageId { get; set; }
        public System.DateTime MealDate { get; set; }
        public int MealDishesId { get; set; }
        public string MealItemName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual MealDish MealDish { get; set; }
        public virtual MealPackage MealPackage { get; set; }
    }
}
