//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenusRolePermission
    {
        public int MenusRolePermissionId { get; set; }
        public int MenuId { get; set; }
        public int RoleId { get; set; }
        public bool IsViewRights { get; set; }
        public bool IsAddRights { get; set; }
        public bool IsModifyRights { get; set; }
        public bool IsDeleteRights { get; set; }
        public bool IsAssignRights { get; set; }
        public bool IsApproveRights { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Role Role { get; set; }
    }
}
