//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlySalaryDisbursement
    {
        public int MonthlySalaryDisbursementId { get; set; }
        public string DocFile { get; set; }
        public string ExcelFile { get; set; }
        public string PdfFile { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<double> TotalPaid { get; set; }
    }
}
