//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnshoreManager
    {
        public OnshoreManager()
        {
            this.UsersOnshoreMgrMappings = new HashSet<UsersOnshoreMgrMapping>();
        }
    
        public long OnshoreMgrId { get; set; }
        public string ManagerName { get; set; }
        public string EmailId { get; set; }
        public int ClientId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<UsersOnshoreMgrMapping> UsersOnshoreMgrMappings { get; set; }
    }
}
