//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutingRequest
    {
        public OutingRequest()
        {
            this.OutingRequestDetails = new HashSet<OutingRequestDetail>();
            this.OutingRequestHistories = new HashSet<OutingRequestHistory>();
        }
    
        public long OutingRequestId { get; set; }
        public int OutingTypeId { get; set; }
        public int UserId { get; set; }
        public long FromDateId { get; set; }
        public long TillDateId { get; set; }
        public string Reason { get; set; }
        public string PrimaryContactNo { get; set; }
        public string AlternativeContactNo { get; set; }
        public long StatusId { get; set; }
        public Nullable<int> NextApproverId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual OutingRequestStatu OutingRequestStatu { get; set; }
        public virtual OutingType OutingType { get; set; }
        public virtual ICollection<OutingRequestDetail> OutingRequestDetails { get; set; }
        public virtual ICollection<OutingRequestHistory> OutingRequestHistories { get; set; }
        public virtual DateMaster DateMaster { get; set; }
        public virtual DateMaster DateMaster1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
