//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutingRequestStatu
    {
        public OutingRequestStatu()
        {
            this.OutingRequests = new HashSet<OutingRequest>();
            this.OutingRequestDetails = new HashSet<OutingRequestDetail>();
            this.OutingRequestHistories = new HashSet<OutingRequestHistory>();
            this.TempUserShifts = new HashSet<TempUserShift>();
            this.TempUserShiftDetails = new HashSet<TempUserShiftDetail>();
            this.TempUserShiftHistories = new HashSet<TempUserShiftHistory>();
        }
    
        public long StatusId { get; set; }
        public string Status { get; set; }
        public string StatusCode { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual ICollection<OutingRequest> OutingRequests { get; set; }
        public virtual ICollection<OutingRequestDetail> OutingRequestDetails { get; set; }
        public virtual ICollection<OutingRequestHistory> OutingRequestHistories { get; set; }
        public virtual ICollection<TempUserShift> TempUserShifts { get; set; }
        public virtual ICollection<TempUserShiftDetail> TempUserShiftDetails { get; set; }
        public virtual ICollection<TempUserShiftHistory> TempUserShiftHistories { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
