//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PimcoUser
    {
        public PimcoUser()
        {
            this.PimcoUserExpirations = new HashSet<PimcoUserExpiration>();
        }
    
        public long PimcoUserId { get; set; }
        public int GeminiUserId { get; set; }
        public string PimcoEmployeeId { get; set; }
        public string PimcoManagerName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<PimcoUserExpiration> PimcoUserExpirations { get; set; }
        public virtual User User { get; set; }
    }
}
