//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PimcoAchievementDetail
    {
        public int PimcoAchievementDetailId { get; set; }
        public int PimcoAchievementId { get; set; }
        public string Achievement { get; set; }
        public string Purpose { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ProjectId { get; set; }
    
        public virtual PimcoAchievement PimcoAchievement { get; set; }
        public virtual PimcoProject PimcoProject { get; set; }
    }
}
