//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PimcoProject
    {
        public PimcoProject()
        {
            this.PimcoAchievementDetails = new HashSet<PimcoAchievementDetail>();
            this.PimcoMonthlyAchievementDetails = new HashSet<PimcoMonthlyAchievementDetail>();
            this.PimcoProjectTeamMembers = new HashSet<PimcoProjectTeamMember>();
        }
    
        public int PimcoProjectId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int ParentProjectId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public long VerticalId { get; set; }
        public long StatusId { get; set; }
    
        public virtual ICollection<PimcoAchievementDetail> PimcoAchievementDetails { get; set; }
        public virtual ICollection<PimcoMonthlyAchievementDetail> PimcoMonthlyAchievementDetails { get; set; }
        public virtual PimcoProjectVertical PimcoProjectVertical { get; set; }
        public virtual ProjectStatu ProjectStatu { get; set; }
        public virtual ICollection<PimcoProjectTeamMember> PimcoProjectTeamMembers { get; set; }
    }
}
