//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PimcoUserExpiration
    {
        public long PimcoUserExpirationId { get; set; }
        public long PimcoUserId { get; set; }
        public System.DateTime UserValidFromDate { get; set; }
        public System.DateTime UserValidToDate { get; set; }
        public bool IsAcknowledged { get; set; }
        public Nullable<int> AcknowledgedBy { get; set; }
        public Nullable<System.DateTime> AcknowledgedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual PimcoUser PimcoUser { get; set; }
    }
}
