//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PimcoProjectTeamMember
    {
        public long RecordId { get; set; }
        public int PimcoProjectId { get; set; }
        public int UserId { get; set; }
        public string ProjectRole { get; set; }
        public System.DateTime AllocatedFrom { get; set; }
        public Nullable<System.DateTime> AllocatedTill { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual PimcoProject PimcoProject { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
