//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.FinalLoggedTasks = new HashSet<FinalLoggedTask>();
            this.LoggedTasks = new HashSet<LoggedTask>();
            this.ProjectPrefrences = new HashSet<ProjectPrefrence>();
            this.ProjectTeamMembers = new HashSet<ProjectTeamMember>();
        }
    
        public long ProjectId { get; set; }
        public Nullable<long> ParentProjectId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public long VerticalId { get; set; }
        public long IndustryTypeId { get; set; }
        public long StatusId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual ICollection<FinalLoggedTask> FinalLoggedTasks { get; set; }
        public virtual ICollection<LoggedTask> LoggedTasks { get; set; }
        public virtual ProjectIndustryType ProjectIndustryType { get; set; }
        public virtual ICollection<ProjectPrefrence> ProjectPrefrences { get; set; }
        public virtual ProjectStatu ProjectStatu { get; set; }
        public virtual ProjectVertical ProjectVertical { get; set; }
        public virtual ICollection<ProjectTeamMember> ProjectTeamMembers { get; set; }
        public virtual User User { get; set; }
    }
}
