//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMaster
    {
        public ProjectMaster()
        {
            this.UserClientSideManagerAndProjectMappings = new HashSet<UserClientSideManagerAndProjectMapping>();
        }
    
        public long ProjectId { get; set; }
        public long ClientId { get; set; }
        public long ClientResourceId { get; set; }
        public string ProjectName { get; set; }
        public string ProjectCode { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public string FriendlyName { get; set; }
    
        public virtual ClientMaster ClientMaster { get; set; }
        public virtual ICollection<UserClientSideManagerAndProjectMapping> UserClientSideManagerAndProjectMappings { get; set; }
    }
}
