//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referral
    {
        public Referral()
        {
            this.ReferralDetails = new HashSet<ReferralDetail>();
        }
    
        public int ReferralId { get; set; }
        public System.DateTime OpeningFrom { get; set; }
        public System.DateTime OpeningTill { get; set; }
        public string Profile { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public bool IsPositionClosed { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<int> HiringProfileId { get; set; }
    
        public virtual ICollection<ReferralDetail> ReferralDetails { get; set; }
    }
}
