//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralDetail
    {
        public ReferralDetail()
        {
            this.ReferralReviews = new HashSet<ReferralReview>();
        }
    
        public int ReferralDetailId { get; set; }
        public int ReferralId { get; set; }
        public string RefereeName { get; set; }
        public string RelationWithReferee { get; set; }
        public string Resume { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ReferredById { get; set; }
    
        public virtual ICollection<ReferralReview> ReferralReviews { get; set; }
        public virtual Referral Referral { get; set; }
    }
}
