//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralReview
    {
        public int ReferralReviewId { get; set; }
        public int ReferralDetailId { get; set; }
        public int ForwardedToId { get; set; }
        public string CommentsByReviewer { get; set; }
        public int ReferredById { get; set; }
        public Nullable<int> IsRelevant { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual ReferralDetail ReferralDetail { get; set; }
    }
}
