//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReimbursementCategory
    {
        public ReimbursementCategory()
        {
            this.ReimbursementDetails = new HashSet<ReimbursementDetail>();
        }
    
        public int ReimbursementCategoryId { get; set; }
        public int ReimbursementTypeId { get; set; }
        public string ReimbursementName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual ReimbursementType ReimbursementType { get; set; }
        public virtual ICollection<ReimbursementDetail> ReimbursementDetails { get; set; }
    }
}
