//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReimbursementStatu
    {
        public ReimbursementStatu()
        {
            this.ReimbursementHistories = new HashSet<ReimbursementHistory>();
            this.ReimbursementRequests = new HashSet<ReimbursementRequest>();
        }
    
        public int StatusId { get; set; }
        public string Status { get; set; }
        public string StatusCode { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual ICollection<ReimbursementHistory> ReimbursementHistories { get; set; }
        public virtual ICollection<ReimbursementRequest> ReimbursementRequests { get; set; }
    }
}
