//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReimbursementHistory
    {
        public long ReimbursementHistoryId { get; set; }
        public long ReimbursementRequestId { get; set; }
        public int StatusId { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
    
        public virtual ReimbursementStatu ReimbursementStatu { get; set; }
        public virtual ReimbursementRequest ReimbursementRequest { get; set; }
    }
}
