//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReimbursementDetail
    {
        public long ReimbursementDetailId { get; set; }
        public long ReimbursementRequestId { get; set; }
        public int ReimbursementCategoryId { get; set; }
        public string DocumentPath { get; set; }
        public string DocumentName { get; set; }
        public string BillNo { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date { get; set; }
        public string Remarks { get; set; }
        public bool IsDocumentValid { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual ReimbursementCategory ReimbursementCategory { get; set; }
        public virtual ReimbursementRequest ReimbursementRequest { get; set; }
    }
}
