//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReimbursementRequest
    {
        public ReimbursementRequest()
        {
            this.ReimbursementDetails = new HashSet<ReimbursementDetail>();
            this.ReimbursementHistories = new HashSet<ReimbursementHistory>();
        }
    
        public long ReimbursementRequestId { get; set; }
        public int UserId { get; set; }
        public int ReimbursementTypeId { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public decimal ReimbRequestedAmt { get; set; }
        public Nullable<decimal> ReimbApprovedAmt { get; set; }
        public Nullable<int> NextApproverId { get; set; }
        public string Remarks { get; set; }
        public int StatusId { get; set; }
        public bool IsReferredBack { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual ICollection<ReimbursementDetail> ReimbursementDetails { get; set; }
        public virtual ICollection<ReimbursementHistory> ReimbursementHistories { get; set; }
        public virtual ReimbursementStatu ReimbursementStatu { get; set; }
        public virtual ReimbursementType ReimbursementType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
