//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestLnsaHistory
    {
        public long RequestLnsaHistoryId { get; set; }
        public long RequestId { get; set; }
        public long StatusId { get; set; }
        public string Remarks { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual LNSAStatusMaster LNSAStatusMaster { get; set; }
        public virtual RequestLnsa RequestLnsa { get; set; }
    }
}
