//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestDetail
    {
        public int RequestDetailId { get; set; }
        public Nullable<int> LeaveRequestId { get; set; }
        public Nullable<int> AttendanceRequestId { get; set; }
        public Nullable<int> MeetingRequestId { get; set; }
    
        public virtual AttendanceCorrectionRequest AttendanceCorrectionRequest { get; set; }
        public virtual LeaveRequest LeaveRequest { get; set; }
        public virtual RequestDetail RequestDetail1 { get; set; }
        public virtual RequestDetail RequestDetail2 { get; set; }
    }
}
