//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestCompOff
    {
        public RequestCompOff()
        {
            this.RequestCompOffDetails = new HashSet<RequestCompOffDetail>();
        }
    
        public long RequestId { get; set; }
        public long DateId { get; set; }
        public int NoOfDays { get; set; }
        public string Reason { get; set; }
        public long StatusId { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public bool IsLapsed { get; set; }
        public System.DateTime LapseDate { get; set; }
        public bool IsAvailed { get; set; }
    
        public virtual LeaveStatusMaster LeaveStatusMaster { get; set; }
        public virtual ICollection<RequestCompOffDetail> RequestCompOffDetails { get; set; }
        public virtual DateMaster DateMaster { get; set; }
        public virtual User User { get; set; }
    }
}
