//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestCompOffDetail
    {
        public long RequestCompOffDetailId { get; set; }
        public long RequestId { get; set; }
        public Nullable<long> LeaveRequestApplicationId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public Nullable<long> LegitimateLeaveRequestId { get; set; }
    
        public virtual LeaveRequestApplication LeaveRequestApplication { get; set; }
        public virtual LegitimateLeaveRequest LegitimateLeaveRequest { get; set; }
        public virtual RequestCompOff RequestCompOff { get; set; }
    }
}
