//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatMaster
    {
        public SeatMaster()
        {
            this.SeatAllocationDetails = new HashSet<SeatAllocationDetail>();
            this.SeatCheckDetails = new HashSet<SeatCheckDetail>();
        }
    
        public int SeatId { get; set; }
        public int PremisesFloorId { get; set; }
        public string SeatNumber { get; set; }
        public int SeatTypeId { get; set; }
        public Nullable<int> BayNumber { get; set; }
        public int SeatStatusId { get; set; }
        public bool IsChecked { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual LocationPremisesListMaster LocationPremisesListMaster { get; set; }
        public virtual ICollection<SeatAllocationDetail> SeatAllocationDetails { get; set; }
        public virtual ICollection<SeatCheckDetail> SeatCheckDetails { get; set; }
        public virtual SeatStatusMaster SeatStatusMaster { get; set; }
        public virtual SeatTypeMaster SeatTypeMaster { get; set; }
    }
}
