//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatDetailTemp
    {
        public int SeatId { get; set; }
        public int PremisesFloorId { get; set; }
        public string SeatNumber { get; set; }
        public int SeatTypeId { get; set; }
        public Nullable<int> BayNumber { get; set; }
        public int SeatStatusId { get; set; }
        public bool IsChecked { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> AllocationTypeId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> AllocationFrom { get; set; }
        public Nullable<int> OnboardingId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> SystemRequirementId { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public string BlockingReason { get; set; }
        public Nullable<System.DateTime> BlockingFrom { get; set; }
    }
}
