//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareDocument
    {
        public int ShareDocId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public Nullable<int> ShareTo { get; set; }
        public Nullable<int> ShareBy { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
