//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftMaster
    {
        public ShiftMaster()
        {
            this.UserShiftMappings = new HashSet<UserShiftMapping>();
            this.TempUserShifts = new HashSet<TempUserShift>();
        }
    
        public long ShiftId { get; set; }
        public string ShiftName { get; set; }
        public System.TimeSpan InTime { get; set; }
        public System.TimeSpan OutTime { get; set; }
        public Nullable<System.TimeSpan> WorkingHours { get; set; }
        public bool IsWeekEnd { get; set; }
        public bool IsNight { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual ICollection<UserShiftMapping> UserShiftMappings { get; set; }
        public virtual ICollection<TempUserShift> TempUserShifts { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
