//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillType
    {
        public SkillType()
        {
            this.UserSkills = new HashSet<UserSkill>();
        }
    
        public int SkillTypeId { get; set; }
        public string SkillTypeName { get; set; }
        public int Sequence { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public bool IsVisibleToUser { get; set; }
    
        public virtual ICollection<UserSkill> UserSkills { get; set; }
    }
}
