//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Locations = new HashSet<Location>();
            this.UserAddressDetails = new HashSet<UserAddressDetail>();
            this.TempUserAddressDetails = new HashSet<TempUserAddressDetail>();
        }
    
        public int StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<UserAddressDetail> UserAddressDetails { get; set; }
        public virtual ICollection<TempUserAddressDetail> TempUserAddressDetails { get; set; }
    }
}
