//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskSubDetail2
    {
        public TaskSubDetail2()
        {
            this.FinalLoggedTasks = new HashSet<FinalLoggedTask>();
            this.LoggedTasks = new HashSet<LoggedTask>();
            this.TaskTemplates = new HashSet<TaskTemplate>();
            this.TaskTypeTaskSubDetail2Mapping = new HashSet<TaskTypeTaskSubDetail2Mapping>();
        }
    
        public long TaskSubDetail2Id { get; set; }
        public string TaskSubDetail2Name { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual ICollection<FinalLoggedTask> FinalLoggedTasks { get; set; }
        public virtual ICollection<LoggedTask> LoggedTasks { get; set; }
        public virtual ICollection<TaskTemplate> TaskTemplates { get; set; }
        public virtual ICollection<TaskTypeTaskSubDetail2Mapping> TaskTypeTaskSubDetail2Mapping { get; set; }
        public virtual User User { get; set; }
    }
}
