//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskType
    {
        public TaskType()
        {
            this.FinalLoggedTasks = new HashSet<FinalLoggedTask>();
            this.LoggedTasks = new HashSet<LoggedTask>();
            this.TaskTeamTaskTypeMappings = new HashSet<TaskTeamTaskTypeMapping>();
            this.TaskTemplates = new HashSet<TaskTemplate>();
            this.TaskTypeTaskSubDetail1Mapping = new HashSet<TaskTypeTaskSubDetail1Mapping>();
            this.TaskTypeTaskSubDetail2Mapping = new HashSet<TaskTypeTaskSubDetail2Mapping>();
        }
    
        public long TaskTypeId { get; set; }
        public string TaskTypeName { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual ICollection<FinalLoggedTask> FinalLoggedTasks { get; set; }
        public virtual ICollection<LoggedTask> LoggedTasks { get; set; }
        public virtual ICollection<TaskTeamTaskTypeMapping> TaskTeamTaskTypeMappings { get; set; }
        public virtual ICollection<TaskTemplate> TaskTemplates { get; set; }
        public virtual ICollection<TaskTypeTaskSubDetail1Mapping> TaskTypeTaskSubDetail1Mapping { get; set; }
        public virtual ICollection<TaskTypeTaskSubDetail2Mapping> TaskTypeTaskSubDetail2Mapping { get; set; }
        public virtual User User { get; set; }
    }
}
