//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamGoalHistory
    {
        public long TeamGoalHistoryId { get; set; }
        public long TeamGoalId { get; set; }
        public long StartDateId { get; set; }
        public long EndDateId { get; set; }
        public string Goal { get; set; }
        public long GoalStatusId { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public int GoalCategoryId { get; set; }
    
        public virtual DateMaster DateMaster { get; set; }
        public virtual DateMaster DateMaster1 { get; set; }
        public virtual GoalCategory GoalCategory { get; set; }
        public virtual GoalStatu GoalStatu { get; set; }
        public virtual User User { get; set; }
    }
}
