//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.AppraisalSettings = new HashSet<AppraisalSetting>();
            this.AttendanceReportAccesses = new HashSet<AttendanceReportAccess>();
            this.EmpAppraisalSettings = new HashSet<EmpAppraisalSetting>();
            this.EmpAppraisalSettingLogs = new HashSet<EmpAppraisalSettingLog>();
            this.TeamEmailTypeMappings = new HashSet<TeamEmailTypeMapping>();
            this.TimeSheetReportAccesses = new HashSet<TimeSheetReportAccess>();
            this.UserTeamMappings = new HashSet<UserTeamMapping>();
            this.TeamGoals = new HashSet<TeamGoal>();
        }
    
        public long TeamId { get; set; }
        public string TeamName { get; set; }
        public int WeekDayId { get; set; }
        public bool IsReminderEmailsEnabled { get; set; }
        public bool IsAttendanceEmailsEnabled { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public int TeamHeadId { get; set; }
        public int DepartmentId { get; set; }
        public int ParentTeamId { get; set; }
    
        public virtual ICollection<AppraisalSetting> AppraisalSettings { get; set; }
        public virtual ICollection<AttendanceReportAccess> AttendanceReportAccesses { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<EmpAppraisalSetting> EmpAppraisalSettings { get; set; }
        public virtual ICollection<EmpAppraisalSettingLog> EmpAppraisalSettingLogs { get; set; }
        public virtual WeekDay WeekDay { get; set; }
        public virtual ICollection<TeamEmailTypeMapping> TeamEmailTypeMappings { get; set; }
        public virtual ICollection<TimeSheetReportAccess> TimeSheetReportAccesses { get; set; }
        public virtual ICollection<UserTeamMapping> UserTeamMappings { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TeamGoal> TeamGoals { get; set; }
    }
}
