//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamRole
    {
        public TeamRole()
        {
            this.UserTeamMappings = new HashSet<UserTeamMapping>();
        }
    
        public int TeamRoleId { get; set; }
        public string TeamRoleName { get; set; }
        public int AccessSequence { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual ICollection<UserTeamMapping> UserTeamMappings { get; set; }
    }
}
