//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempUserShift
    {
        public TempUserShift()
        {
            this.TempUserShiftDetails = new HashSet<TempUserShiftDetail>();
            this.TempUserShiftHistories = new HashSet<TempUserShiftHistory>();
        }
    
        public long TempUserShiftId { get; set; }
        public int UserId { get; set; }
        public long ShiftId { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public long StatusId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual OutingRequestStatu OutingRequestStatu { get; set; }
        public virtual ShiftMaster ShiftMaster { get; set; }
        public virtual ICollection<TempUserShiftDetail> TempUserShiftDetails { get; set; }
        public virtual ICollection<TempUserShiftHistory> TempUserShiftHistories { get; set; }
        public virtual User User { get; set; }
    }
}
