//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempUserRegistration
    {
        public TempUserRegistration()
        {
            this.TempUserAddressDetails = new HashSet<TempUserAddressDetail>();
        }
    
        public long RegistrationId { get; set; }
        public string UserName { get; set; }
        public string EmailId { get; set; }
        public string TempUserGuid { get; set; }
        public Nullable<bool> IsGuidExpired { get; set; }
        public Nullable<System.DateTime> GuidExpiryDate { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string BloodGroup { get; set; }
        public string MobileNumber { get; set; }
        public string EmergencyContactNumber { get; set; }
        public string PersonalEmailId { get; set; }
        public Nullable<int> MaritalStatusId { get; set; }
        public string InsuranceAmount { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<System.DateTime> VerificationDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsFresher { get; set; }
        public string LastEmployerName { get; set; }
        public string LastEmployerLocation { get; set; }
        public string LastJobDesignation { get; set; }
        public string LastJobTenure { get; set; }
        public string LastJobUAN { get; set; }
        public string JobLeavingReason { get; set; }
        public string PanCardId { get; set; }
        public string AadhaarCardId { get; set; }
        public string VoterCardId { get; set; }
        public string DrivingLicenseId { get; set; }
        public string PassportId { get; set; }
        public string Remarks { get; set; }
        public string PhotoFileName { get; set; }
        public string ADUserName { get; set; }
    
        public virtual ICollection<TempUserAddressDetail> TempUserAddressDetails { get; set; }
    }
}
