//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timezone
    {
        public int TimeZoneId { get; set; }
        public string BaseUTCOffset { get; set; }
        public string DayLightName { get; set; }
        public string DisplayName { get; set; }
        public string Id { get; set; }
        public string StatndardName { get; set; }
        public Nullable<bool> SupportsDayLightSavingTime { get; set; }
    }
}
