//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheetFinalTask
    {
        public long RecordId { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public long WeekId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int WeekNo { get; set; }
        public int Year { get; set; }
        public System.DateTime TaskDate { get; set; }
        public long ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string TaskDescription { get; set; }
        public string TaskTeamName { get; set; }
        public string TaskType { get; set; }
        public string TaskSubDetail1 { get; set; }
        public string TaskSubDetail2 { get; set; }
        public decimal TimeSpent { get; set; }
        public string TeamName { get; set; }
        public int Status { get; set; }
        public Nullable<bool> ConsiderInReports { get; set; }
    }
}
