//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        public TimeSheet()
        {
            this.TimeSheetTaskMappings = new HashSet<TimeSheetTaskMapping>();
        }
    
        public long TimeSheetId { get; set; }
        public int WeekNo { get; set; }
        public int Year { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public decimal TotalHoursLogged { get; set; }
        public int Status { get; set; }
        public string UserRemarks { get; set; }
        public string ApproverRemarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public bool IsSubmissionOnTime { get; set; }
        public Nullable<bool> IsTimeSheetEnabled { get; set; }
    
        public virtual ICollection<TimeSheetTaskMapping> TimeSheetTaskMappings { get; set; }
        public virtual User User { get; set; }
    }
}
