//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentScore
    {
        public long TournamentScoreId { get; set; }
        public long TournamentScheduleId { get; set; }
        public long TournamentTeamId { get; set; }
        public Nullable<int> G1Score { get; set; }
        public Nullable<int> G2Score { get; set; }
        public Nullable<int> G3Score { get; set; }
        public Nullable<int> G4Score { get; set; }
        public Nullable<int> G5Score { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual TournamentSchedule TournamentSchedule { get; set; }
        public virtual TournamentTeam TournamentTeam { get; set; }
    }
}
