//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentSchedule
    {
        public TournamentSchedule()
        {
            this.TournamentScores = new HashSet<TournamentScore>();
        }
    
        public long TournamentScheduleId { get; set; }
        public System.DateTime TournamentDate { get; set; }
        public long TournamentTeamId { get; set; }
        public long TournamentVSTeamId { get; set; }
        public int Round { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual ICollection<TournamentScore> TournamentScores { get; set; }
        public virtual TournamentTeam TournamentTeam { get; set; }
        public virtual TournamentTeam TournamentTeam1 { get; set; }
    }
}
