//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentTeam
    {
        public TournamentTeam()
        {
            this.TournamentSchedules = new HashSet<TournamentSchedule>();
            this.TournamentSchedules1 = new HashSet<TournamentSchedule>();
            this.TournamentScores = new HashSet<TournamentScore>();
        }
    
        public long TournamentTeamId { get; set; }
        public int TournamentCategoryId { get; set; }
        public string ParticipantsUserIds { get; set; }
        public string Group { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual TournamentCategory TournamentCategory { get; set; }
        public virtual ICollection<TournamentSchedule> TournamentSchedules { get; set; }
        public virtual ICollection<TournamentSchedule> TournamentSchedules1 { get; set; }
        public virtual ICollection<TournamentScore> TournamentScores { get; set; }
    }
}
