//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentCategory
    {
        public TournamentCategory()
        {
            this.TournamentTeams = new HashSet<TournamentTeam>();
        }
    
        public int TournamentCategoryId { get; set; }
        public string CategoryCode { get; set; }
        public string Category { get; set; }
        public int TournamentId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual Tournament Tournament { get; set; }
        public virtual ICollection<TournamentTeam> TournamentTeams { get; set; }
    }
}
