//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public Training()
        {
            this.TrainingDetails = new HashSet<TrainingDetail>();
        }
    
        public int TrainingId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime TentativeDate { get; set; }
        public System.DateTime NominationStartDate { get; set; }
        public System.DateTime NominationEndDate { get; set; }
        public bool IsNominationClosed { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string Document { get; set; }
        public bool IsDocumented { get; set; }
    
        public virtual ICollection<TrainingDetail> TrainingDetails { get; set; }
    }
}
