//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSkill
    {
        public int UserSkillId { get; set; }
        public int SkillId { get; set; }
        public int UserId { get; set; }
        public int SkillLevelId { get; set; }
        public int MonthsOfExperience { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public int SkillTypeId { get; set; }
    
        public virtual Skill Skill { get; set; }
        public virtual SkillLevel SkillLevel { get; set; }
        public virtual SkillType SkillType { get; set; }
        public virtual User User { get; set; }
    }
}
