//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAssetDetail
    {
        public long AssetsRequestId { get; set; }
        public int UserId { get; set; }
        public long AssetId { get; set; }
        public System.DateTime AllocatedFrom { get; set; }
        public Nullable<System.DateTime> AllocatedTill { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsLost { get; set; }
        public bool IsCollected { get; set; }
        public string DeAllocationRemarks { get; set; }
        public Nullable<System.DateTime> CollectedOn { get; set; }
        public Nullable<int> CollectedBy { get; set; }
        public string Department { get; set; }
    }
}
