//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAchievement
    {
        public UserAchievement()
        {
            this.UserAchievementComments = new HashSet<UserAchievementComment>();
        }
    
        public long UserAchievementId { get; set; }
        public long EmpAppraisalSettingId { get; set; }
        public string Achievement { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual EmpAppraisalSetting EmpAppraisalSetting { get; set; }
        public virtual ICollection<UserAchievementComment> UserAchievementComments { get; set; }
        public virtual User User { get; set; }
    }
}
