//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivity
    {
        public long UserActivityId { get; set; }
        public string Activity { get; set; }
        public int VisitedByUserId { get; set; }
        public Nullable<int> VisitedForUserId { get; set; }
        public System.DateTime ActivityDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
