//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccessCard
    {
        public int UserAccessCardId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int AccessCardId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public bool IsFinalised { get; set; }
        public bool IsPimco { get; set; }
        public Nullable<int> StaffUserId { get; set; }
        public System.DateTime AssignedFromDate { get; set; }
        public Nullable<System.DateTime> AssignedTillDate { get; set; }
    
        public virtual AccessCard AccessCard { get; set; }
        public virtual User User { get; set; }
    }
}
