//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int UserDetailId { get; set; }
        public int UserId { get; set; }
        public string PunchId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string DOB { get; set; }
        public int GenderId { get; set; }
        public Nullable<int> MaritalStatusId { get; set; }
        public string BloodGroup { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> TerminateDate { get; set; }
        public Nullable<int> ReportTo { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public string EmergencyContactNumber { get; set; }
        public string PersonalEmailId { get; set; }
        public string ExtensionNumber { get; set; }
        public string InsuranceAmount { get; set; }
        public string PanCardId { get; set; }
        public string AadhaarCardId { get; set; }
        public string VoterCardId { get; set; }
        public string DrivingLicenseId { get; set; }
        public string PassportId { get; set; }
        public string LastEmployerName { get; set; }
        public string LastEmployerLocation { get; set; }
        public string LastJobTenure { get; set; }
        public string JobLeavingReason { get; set; }
        public string UAN { get; set; }
        public Nullable<bool> IsFresher { get; set; }
        public string LastJobDesignation { get; set; }
        public Nullable<int> AppraisalCycleId { get; set; }
        public Nullable<int> ProjectManagerId { get; set; }
        public bool IsDOBPublic { get; set; }
        public bool IsImageVerified { get; set; }
        public Nullable<int> ProbationPeriodMonths { get; set; }
        public bool IsEligibleForLeave { get; set; }
        public Nullable<System.DateTime> FTEDate { get; set; }
        public string WorkStationNo { get; set; }
        public bool IsUserVerified { get; set; }
    
        public virtual AppraisalCycle AppraisalCycle { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
