//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAchievementComment
    {
        public long UserAchievementCommentId { get; set; }
        public long UserAchievementId { get; set; }
        public string AppraiserComment { get; set; }
        public string ApproverComment { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual UserAchievement UserAchievement { get; set; }
    }
}
