//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFamilyDetail
    {
        public long UserFamilyDetailId { get; set; }
        public int UserId { get; set; }
        public int RelationshipId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public int GenderId { get; set; }
        public Nullable<int> OccupationId { get; set; }
        public string Company { get; set; }
        public string Designation { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Occupation Occupation { get; set; }
        public virtual Relationship Relationship { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
