//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivityLog
    {
        public long UserActivityLogId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public string IPAddress { get; set; }
        public string BrowserInfo { get; set; }
        public string ActivityStatus { get; set; }
        public string ActivityDetail { get; set; }
        public System.DateTime LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public string ClientInfo { get; set; }
        public string Device { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string TimeZone { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string ISP { get; set; }
    }
}
