//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAchievementForMidYear
    {
        public long UserAchievementId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> AppraisalCycleId { get; set; }
        public string Achievement { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual AppraisalCycle AppraisalCycle { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
