//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AsquareUserMappings = new HashSet<AsquareUserMapping>();
            this.AssetDetails = new HashSet<AssetDetail>();
            this.AssetRequests = new HashSet<AssetRequest>();
            this.AssetTransactions = new HashSet<AssetTransaction>();
            this.AssetTypes = new HashSet<AssetType>();
            this.AttendanceDataChangeRequestCategories = new HashSet<AttendanceDataChangeRequestCategory>();
            this.AttendanceDataChangeRequestCategories1 = new HashSet<AttendanceDataChangeRequestCategory>();
            this.AttendanceReportAccesses = new HashSet<AttendanceReportAccess>();
            this.AttendanceReportAccesses1 = new HashSet<AttendanceReportAccess>();
            this.AttendanceStatusMasters = new HashSet<AttendanceStatusMaster>();
            this.AttendanceStatusMasters1 = new HashSet<AttendanceStatusMaster>();
            this.AttendanceUploadHistoryAsquares = new HashSet<AttendanceUploadHistoryAsquare>();
            this.CabRequests = new HashSet<CabRequest>();
            this.CertificationsAndRewards = new HashSet<CertificationsAndReward>();
            this.ChangeExtnRequests = new HashSet<ChangeExtnRequest>();
            this.ChangeExtnRequests1 = new HashSet<ChangeExtnRequest>();
            this.ClientResourceMasters = new HashSet<ClientResourceMaster>();
            this.ClientSideManagerMasters = new HashSet<ClientSideManagerMaster>();
            this.DashboardWidgetUserPermissions = new HashSet<DashboardWidgetUserPermission>();
            this.DateWiseAttendances = new HashSet<DateWiseAttendance>();
            this.DateWiseAttendances1 = new HashSet<DateWiseAttendance>();
            this.DateWiseAttendances2 = new HashSet<DateWiseAttendance>();
            this.DateWiseAttendanceAsquares = new HashSet<DateWiseAttendanceAsquare>();
            this.DateWiseAttendanceAsquares1 = new HashSet<DateWiseAttendanceAsquare>();
            this.DateWiseAttendanceAsquares2 = new HashSet<DateWiseAttendanceAsquare>();
            this.DateWisePunchInDatas = new HashSet<DateWisePunchInData>();
            this.Departments = new HashSet<Department>();
            this.DepartmentWiseAssetLimits = new HashSet<DepartmentWiseAssetLimit>();
            this.Divisions = new HashSet<Division>();
            this.Documents = new HashSet<Document>();
            this.DocumentPermissionGroups = new HashSet<DocumentPermissionGroup>();
            this.DocumentPermissionGroupPermissions = new HashSet<DocumentPermissionGroupPermission>();
            this.EmpAppraisalSettings = new HashSet<EmpAppraisalSetting>();
            this.EmpAppraisalSettings1 = new HashSet<EmpAppraisalSetting>();
            this.EmpAppraisalSettings2 = new HashSet<EmpAppraisalSetting>();
            this.EmpAppraisalSettings3 = new HashSet<EmpAppraisalSetting>();
            this.EmpAppraisalSettingLogs = new HashSet<EmpAppraisalSettingLog>();
            this.EmpAppraisalSettingLogs1 = new HashSet<EmpAppraisalSettingLog>();
            this.EmpAppraisalSettingLogs2 = new HashSet<EmpAppraisalSettingLog>();
            this.EmpAppraisalSettingLogs3 = new HashSet<EmpAppraisalSettingLog>();
            this.EmployeeProfiles = new HashSet<EmployeeProfile>();
            this.EmployeeProfiles1 = new HashSet<EmployeeProfile>();
            this.EmployeeWiseWeekOffs = new HashSet<EmployeeWiseWeekOff>();
            this.ExcludedUsersForAttendanceImports = new HashSet<ExcludedUsersForAttendanceImport>();
            this.ExcludedUsersForAttendanceImports1 = new HashSet<ExcludedUsersForAttendanceImport>();
            this.FinalLoggedTasks = new HashSet<FinalLoggedTask>();
            this.Forms = new HashSet<Form>();
            this.Forms1 = new HashSet<Form>();
            this.GoalStatus = new HashSet<GoalStatu>();
            this.GoalStatus1 = new HashSet<GoalStatu>();
            this.GSOCProjectSubscribers = new HashSet<GSOCProjectSubscriber>();
            this.InvoiceRequests = new HashSet<InvoiceRequest>();
            this.LeaveBalances = new HashSet<LeaveBalance>();
            this.LeaveBalances1 = new HashSet<LeaveBalance>();
            this.LeaveBalances2 = new HashSet<LeaveBalance>();
            this.LeaveBalanceHistories = new HashSet<LeaveBalanceHistory>();
            this.LeaveHistories = new HashSet<LeaveHistory>();
            this.LeaveRequestApplications = new HashSet<LeaveRequestApplication>();
            this.LeaveRequestApplications1 = new HashSet<LeaveRequestApplication>();
            this.LeaveRequestApplications2 = new HashSet<LeaveRequestApplication>();
            this.LeaveRequestApplications3 = new HashSet<LeaveRequestApplication>();
            this.LeaveStatusMasters = new HashSet<LeaveStatusMaster>();
            this.LeaveStatusMasters1 = new HashSet<LeaveStatusMaster>();
            this.LeaveTypeMasters = new HashSet<LeaveTypeMaster>();
            this.LeaveTypeMasters1 = new HashSet<LeaveTypeMaster>();
            this.LegitimateLeaveRequests = new HashSet<LegitimateLeaveRequest>();
            this.LegitimateLeaveRequests1 = new HashSet<LegitimateLeaveRequest>();
            this.LegitimateLeaveRequests2 = new HashSet<LegitimateLeaveRequest>();
            this.LegitimateLeaveRequests3 = new HashSet<LegitimateLeaveRequest>();
            this.LegitimateLeaveRequests4 = new HashSet<LegitimateLeaveRequest>();
            this.LegitimateLeaveRequestHistories = new HashSet<LegitimateLeaveRequestHistory>();
            this.LegitimateLeaveStatus = new HashSet<LegitimateLeaveStatu>();
            this.LegitimateLeaveStatus1 = new HashSet<LegitimateLeaveStatu>();
            this.ListofHolidays = new HashSet<ListofHoliday>();
            this.LoggedTasks = new HashSet<LoggedTask>();
            this.MealPackageFeedbacks = new HashSet<MealPackageFeedback>();
            this.MenusApprovalLevels = new HashSet<MenusApprovalLevel>();
            this.MenusUserDelegations = new HashSet<MenusUserDelegation>();
            this.MenusUserDelegations1 = new HashSet<MenusUserDelegation>();
            this.MenusUserPermissions = new HashSet<MenusUserPermission>();
            this.News = new HashSet<News>();
            this.OutingRequests = new HashSet<OutingRequest>();
            this.OutingRequests1 = new HashSet<OutingRequest>();
            this.OutingRequests2 = new HashSet<OutingRequest>();
            this.OutingRequestHistories = new HashSet<OutingRequestHistory>();
            this.OutingRequestStatus = new HashSet<OutingRequestStatu>();
            this.OutingRequestStatus1 = new HashSet<OutingRequestStatu>();
            this.PimcoAchievements = new HashSet<PimcoAchievement>();
            this.PimcoMonthlyAchievements = new HashSet<PimcoMonthlyAchievement>();
            this.PimcoProjectTeamMembers = new HashSet<PimcoProjectTeamMember>();
            this.PimcoProjectTeamMembers1 = new HashSet<PimcoProjectTeamMember>();
            this.PimcoProjectVerticals = new HashSet<PimcoProjectVertical>();
            this.PimcoUsers = new HashSet<PimcoUser>();
            this.Policies = new HashSet<Policy>();
            this.Policies1 = new HashSet<Policy>();
            this.ProfessionalAndEducationalExperiences = new HashSet<ProfessionalAndEducationalExperience>();
            this.ProfileRequests = new HashSet<ProfileRequest>();
            this.ProfileRequests1 = new HashSet<ProfileRequest>();
            this.ProfileRequests2 = new HashSet<ProfileRequest>();
            this.ProjectIndustryTypes = new HashSet<ProjectIndustryType>();
            this.ProjectPrefrences = new HashSet<ProjectPrefrence>();
            this.ProjectPrefrences1 = new HashSet<ProjectPrefrence>();
            this.Projects = new HashSet<Project>();
            this.ProjectStatus = new HashSet<ProjectStatu>();
            this.ProjectTeamMembers = new HashSet<ProjectTeamMember>();
            this.ProjectTeamMembers1 = new HashSet<ProjectTeamMember>();
            this.ProjectVerticals = new HashSet<ProjectVertical>();
            this.ReimbursementRequests = new HashSet<ReimbursementRequest>();
            this.ReimbursementRequests1 = new HashSet<ReimbursementRequest>();
            this.RequestCompOffs = new HashSet<RequestCompOff>();
            this.RequestCompOffHistories = new HashSet<RequestCompOffHistory>();
            this.RequestCompOffHistories1 = new HashSet<RequestCompOffHistory>();
            this.RequestLnsas = new HashSet<RequestLnsa>();
            this.SchedulerActions = new HashSet<SchedulerAction>();
            this.SchedulerActions1 = new HashSet<SchedulerAction>();
            this.SharedGroupDocuments = new HashSet<SharedGroupDocument>();
            this.ShareDocuments = new HashSet<ShareDocument>();
            this.ShareDocuments1 = new HashSet<ShareDocument>();
            this.ShiftMasters = new HashSet<ShiftMaster>();
            this.ShiftMasters1 = new HashSet<ShiftMaster>();
            this.SupportingStaffMembers = new HashSet<SupportingStaffMember>();
            this.TaskSubDetail1 = new HashSet<TaskSubDetail1>();
            this.TaskSubDetail2 = new HashSet<TaskSubDetail2>();
            this.TaskTeams = new HashSet<TaskTeam>();
            this.TaskTeamTaskTypeMappings = new HashSet<TaskTeamTaskTypeMapping>();
            this.TaskTemplates = new HashSet<TaskTemplate>();
            this.TaskTypes = new HashSet<TaskType>();
            this.TaskTypeTaskSubDetail1Mapping = new HashSet<TaskTypeTaskSubDetail1Mapping>();
            this.TaskTypeTaskSubDetail2Mapping = new HashSet<TaskTypeTaskSubDetail2Mapping>();
            this.Teams = new HashSet<Team>();
            this.TempUserShifts = new HashSet<TempUserShift>();
            this.TimeSheets = new HashSet<TimeSheet>();
            this.TimesheetExcludedUsers = new HashSet<TimesheetExcludedUser>();
            this.TimesheetExcludedUsers1 = new HashSet<TimesheetExcludedUser>();
            this.TimesheetExcludedUsers2 = new HashSet<TimesheetExcludedUser>();
            this.TimeSheetReportAccesses = new HashSet<TimeSheetReportAccess>();
            this.TimeSheetReportAccesses1 = new HashSet<TimeSheetReportAccess>();
            this.TrainingDetails = new HashSet<TrainingDetail>();
            this.TrainingDetails1 = new HashSet<TrainingDetail>();
            this.UserPromotionHistories = new HashSet<UserPromotionHistory>();
            this.AssetDetailAttributes = new HashSet<AssetDetailAttribute>();
            this.AssetDetailAttributes1 = new HashSet<AssetDetailAttribute>();
            this.UserDetails = new HashSet<UserDetail>();
            this.UserAccessCards = new HashSet<UserAccessCard>();
            this.UserAchievements = new HashSet<UserAchievement>();
            this.UserAchievementForMidYears = new HashSet<UserAchievementForMidYear>();
            this.UserAchievementForMidYears1 = new HashSet<UserAchievementForMidYear>();
            this.UserActivities = new HashSet<UserActivity>();
            this.UserAddressDetails = new HashSet<UserAddressDetail>();
            this.UserAddressDetails1 = new HashSet<UserAddressDetail>();
            this.UserClientSideManagerAndProjectMappings = new HashSet<UserClientSideManagerAndProjectMapping>();
            this.UserClientSideManagerAndProjectMappings1 = new HashSet<UserClientSideManagerAndProjectMapping>();
            this.UserDetails1 = new HashSet<UserDetail>();
            this.UserFamilyDetails = new HashSet<UserFamilyDetail>();
            this.UserFamilyDetails1 = new HashSet<UserFamilyDetail>();
            this.UserFeedbacks = new HashSet<UserFeedback>();
            this.UserFeedbacks1 = new HashSet<UserFeedback>();
            this.UserForms = new HashSet<UserForm>();
            this.UserForms1 = new HashSet<UserForm>();
            this.UserForms2 = new HashSet<UserForm>();
            this.UserHierarchies = new HashSet<UserHierarchy>();
            this.UserHierarchies1 = new HashSet<UserHierarchy>();
            this.UserLocationHistories = new HashSet<UserLocationHistory>();
            this.UsersHealthInsurances = new HashSet<UsersHealthInsurance>();
            this.UserShiftMappings = new HashSet<UserShiftMapping>();
            this.UserShiftMappings1 = new HashSet<UserShiftMapping>();
            this.UserShiftMappings2 = new HashSet<UserShiftMapping>();
            this.UserSkills = new HashSet<UserSkill>();
            this.UsersOnshoreMgrMappings = new HashSet<UsersOnshoreMgrMapping>();
            this.UsersTokens = new HashSet<UsersToken>();
            this.UserTeamMappings = new HashSet<UserTeamMapping>();
            this.Verticals = new HashSet<Vertical>();
            this.APIs = new HashSet<API>();
            this.APIUserPermissions = new HashSet<APIUserPermission>();
            this.UserGoals = new HashSet<UserGoal>();
            this.UserGoals1 = new HashSet<UserGoal>();
            this.UserGoalHistories = new HashSet<UserGoalHistory>();
            this.GoalCategories = new HashSet<GoalCategory>();
            this.GoalCategories1 = new HashSet<GoalCategory>();
            this.TeamGoals = new HashSet<TeamGoal>();
            this.TeamGoalHistories = new HashSet<TeamGoalHistory>();
        }
    
        public int UserId { get; set; }
        public int LocationId { get; set; }
        public int RoleId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public int UnsuccessfulLoginAttempt { get; set; }
        public Nullable<System.DateTime> LastUnsuccessfulLoginAttemptDate { get; set; }
        public bool IsLocked { get; set; }
        public string AccountLockCode { get; set; }
        public Nullable<int> UnlockedBy { get; set; }
        public bool IsPasswordResetRequired { get; set; }
        public bool IsPasswordResetCodeExpired { get; set; }
        public string PasswordResetCode { get; set; }
        public Nullable<System.DateTime> LastPasswordChanged { get; set; }
        public bool IsActive { get; set; }
        public bool IsSuspended { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public string ADUserName { get; set; }
    
        public virtual ICollection<AsquareUserMapping> AsquareUserMappings { get; set; }
        public virtual ICollection<AssetDetail> AssetDetails { get; set; }
        public virtual ICollection<AssetRequest> AssetRequests { get; set; }
        public virtual ICollection<AssetTransaction> AssetTransactions { get; set; }
        public virtual ICollection<AssetType> AssetTypes { get; set; }
        public virtual ICollection<AttendanceDataChangeRequestCategory> AttendanceDataChangeRequestCategories { get; set; }
        public virtual ICollection<AttendanceDataChangeRequestCategory> AttendanceDataChangeRequestCategories1 { get; set; }
        public virtual ICollection<AttendanceReportAccess> AttendanceReportAccesses { get; set; }
        public virtual ICollection<AttendanceReportAccess> AttendanceReportAccesses1 { get; set; }
        public virtual ICollection<AttendanceStatusMaster> AttendanceStatusMasters { get; set; }
        public virtual ICollection<AttendanceStatusMaster> AttendanceStatusMasters1 { get; set; }
        public virtual ICollection<AttendanceUploadHistoryAsquare> AttendanceUploadHistoryAsquares { get; set; }
        public virtual ICollection<CabRequest> CabRequests { get; set; }
        public virtual ICollection<CertificationsAndReward> CertificationsAndRewards { get; set; }
        public virtual ICollection<ChangeExtnRequest> ChangeExtnRequests { get; set; }
        public virtual ICollection<ChangeExtnRequest> ChangeExtnRequests1 { get; set; }
        public virtual ICollection<ClientResourceMaster> ClientResourceMasters { get; set; }
        public virtual ICollection<ClientSideManagerMaster> ClientSideManagerMasters { get; set; }
        public virtual ICollection<DashboardWidgetUserPermission> DashboardWidgetUserPermissions { get; set; }
        public virtual ICollection<DateWiseAttendance> DateWiseAttendances { get; set; }
        public virtual ICollection<DateWiseAttendance> DateWiseAttendances1 { get; set; }
        public virtual ICollection<DateWiseAttendance> DateWiseAttendances2 { get; set; }
        public virtual ICollection<DateWiseAttendanceAsquare> DateWiseAttendanceAsquares { get; set; }
        public virtual ICollection<DateWiseAttendanceAsquare> DateWiseAttendanceAsquares1 { get; set; }
        public virtual ICollection<DateWiseAttendanceAsquare> DateWiseAttendanceAsquares2 { get; set; }
        public virtual ICollection<DateWisePunchInData> DateWisePunchInDatas { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<DepartmentWiseAssetLimit> DepartmentWiseAssetLimits { get; set; }
        public virtual ICollection<Division> Divisions { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<DocumentPermissionGroup> DocumentPermissionGroups { get; set; }
        public virtual ICollection<DocumentPermissionGroupPermission> DocumentPermissionGroupPermissions { get; set; }
        public virtual ICollection<EmpAppraisalSetting> EmpAppraisalSettings { get; set; }
        public virtual ICollection<EmpAppraisalSetting> EmpAppraisalSettings1 { get; set; }
        public virtual ICollection<EmpAppraisalSetting> EmpAppraisalSettings2 { get; set; }
        public virtual ICollection<EmpAppraisalSetting> EmpAppraisalSettings3 { get; set; }
        public virtual ICollection<EmpAppraisalSettingLog> EmpAppraisalSettingLogs { get; set; }
        public virtual ICollection<EmpAppraisalSettingLog> EmpAppraisalSettingLogs1 { get; set; }
        public virtual ICollection<EmpAppraisalSettingLog> EmpAppraisalSettingLogs2 { get; set; }
        public virtual ICollection<EmpAppraisalSettingLog> EmpAppraisalSettingLogs3 { get; set; }
        public virtual ICollection<EmployeeProfile> EmployeeProfiles { get; set; }
        public virtual ICollection<EmployeeProfile> EmployeeProfiles1 { get; set; }
        public virtual ICollection<EmployeeWiseWeekOff> EmployeeWiseWeekOffs { get; set; }
        public virtual ICollection<ExcludedUsersForAttendanceImport> ExcludedUsersForAttendanceImports { get; set; }
        public virtual ICollection<ExcludedUsersForAttendanceImport> ExcludedUsersForAttendanceImports1 { get; set; }
        public virtual ICollection<FinalLoggedTask> FinalLoggedTasks { get; set; }
        public virtual ICollection<Form> Forms { get; set; }
        public virtual ICollection<Form> Forms1 { get; set; }
        public virtual ICollection<GoalStatu> GoalStatus { get; set; }
        public virtual ICollection<GoalStatu> GoalStatus1 { get; set; }
        public virtual ICollection<GSOCProjectSubscriber> GSOCProjectSubscribers { get; set; }
        public virtual ICollection<InvoiceRequest> InvoiceRequests { get; set; }
        public virtual ICollection<LeaveBalance> LeaveBalances { get; set; }
        public virtual ICollection<LeaveBalance> LeaveBalances1 { get; set; }
        public virtual ICollection<LeaveBalance> LeaveBalances2 { get; set; }
        public virtual ICollection<LeaveBalanceHistory> LeaveBalanceHistories { get; set; }
        public virtual ICollection<LeaveHistory> LeaveHistories { get; set; }
        public virtual ICollection<LeaveRequestApplication> LeaveRequestApplications { get; set; }
        public virtual ICollection<LeaveRequestApplication> LeaveRequestApplications1 { get; set; }
        public virtual ICollection<LeaveRequestApplication> LeaveRequestApplications2 { get; set; }
        public virtual ICollection<LeaveRequestApplication> LeaveRequestApplications3 { get; set; }
        public virtual ICollection<LeaveStatusMaster> LeaveStatusMasters { get; set; }
        public virtual ICollection<LeaveStatusMaster> LeaveStatusMasters1 { get; set; }
        public virtual ICollection<LeaveTypeMaster> LeaveTypeMasters { get; set; }
        public virtual ICollection<LeaveTypeMaster> LeaveTypeMasters1 { get; set; }
        public virtual ICollection<LegitimateLeaveRequest> LegitimateLeaveRequests { get; set; }
        public virtual ICollection<LegitimateLeaveRequest> LegitimateLeaveRequests1 { get; set; }
        public virtual ICollection<LegitimateLeaveRequest> LegitimateLeaveRequests2 { get; set; }
        public virtual ICollection<LegitimateLeaveRequest> LegitimateLeaveRequests3 { get; set; }
        public virtual ICollection<LegitimateLeaveRequest> LegitimateLeaveRequests4 { get; set; }
        public virtual ICollection<LegitimateLeaveRequestHistory> LegitimateLeaveRequestHistories { get; set; }
        public virtual ICollection<LegitimateLeaveStatu> LegitimateLeaveStatus { get; set; }
        public virtual ICollection<LegitimateLeaveStatu> LegitimateLeaveStatus1 { get; set; }
        public virtual ICollection<ListofHoliday> ListofHolidays { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<LoggedTask> LoggedTasks { get; set; }
        public virtual ICollection<MealPackageFeedback> MealPackageFeedbacks { get; set; }
        public virtual ICollection<MenusApprovalLevel> MenusApprovalLevels { get; set; }
        public virtual ICollection<MenusUserDelegation> MenusUserDelegations { get; set; }
        public virtual ICollection<MenusUserDelegation> MenusUserDelegations1 { get; set; }
        public virtual ICollection<MenusUserPermission> MenusUserPermissions { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<OutingRequest> OutingRequests { get; set; }
        public virtual ICollection<OutingRequest> OutingRequests1 { get; set; }
        public virtual ICollection<OutingRequest> OutingRequests2 { get; set; }
        public virtual ICollection<OutingRequestHistory> OutingRequestHistories { get; set; }
        public virtual ICollection<OutingRequestStatu> OutingRequestStatus { get; set; }
        public virtual ICollection<OutingRequestStatu> OutingRequestStatus1 { get; set; }
        public virtual ICollection<PimcoAchievement> PimcoAchievements { get; set; }
        public virtual ICollection<PimcoMonthlyAchievement> PimcoMonthlyAchievements { get; set; }
        public virtual ICollection<PimcoProjectTeamMember> PimcoProjectTeamMembers { get; set; }
        public virtual ICollection<PimcoProjectTeamMember> PimcoProjectTeamMembers1 { get; set; }
        public virtual ICollection<PimcoProjectVertical> PimcoProjectVerticals { get; set; }
        public virtual ICollection<PimcoUser> PimcoUsers { get; set; }
        public virtual ICollection<Policy> Policies { get; set; }
        public virtual ICollection<Policy> Policies1 { get; set; }
        public virtual ICollection<ProfessionalAndEducationalExperience> ProfessionalAndEducationalExperiences { get; set; }
        public virtual ICollection<ProfileRequest> ProfileRequests { get; set; }
        public virtual ICollection<ProfileRequest> ProfileRequests1 { get; set; }
        public virtual ICollection<ProfileRequest> ProfileRequests2 { get; set; }
        public virtual ICollection<ProjectIndustryType> ProjectIndustryTypes { get; set; }
        public virtual ICollection<ProjectPrefrence> ProjectPrefrences { get; set; }
        public virtual ICollection<ProjectPrefrence> ProjectPrefrences1 { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<ProjectStatu> ProjectStatus { get; set; }
        public virtual ICollection<ProjectTeamMember> ProjectTeamMembers { get; set; }
        public virtual ICollection<ProjectTeamMember> ProjectTeamMembers1 { get; set; }
        public virtual ICollection<ProjectVertical> ProjectVerticals { get; set; }
        public virtual ICollection<ReimbursementRequest> ReimbursementRequests { get; set; }
        public virtual ICollection<ReimbursementRequest> ReimbursementRequests1 { get; set; }
        public virtual ICollection<RequestCompOff> RequestCompOffs { get; set; }
        public virtual ICollection<RequestCompOffHistory> RequestCompOffHistories { get; set; }
        public virtual ICollection<RequestCompOffHistory> RequestCompOffHistories1 { get; set; }
        public virtual ICollection<RequestLnsa> RequestLnsas { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<SchedulerAction> SchedulerActions { get; set; }
        public virtual ICollection<SchedulerAction> SchedulerActions1 { get; set; }
        public virtual ICollection<SharedGroupDocument> SharedGroupDocuments { get; set; }
        public virtual ICollection<ShareDocument> ShareDocuments { get; set; }
        public virtual ICollection<ShareDocument> ShareDocuments1 { get; set; }
        public virtual ICollection<ShiftMaster> ShiftMasters { get; set; }
        public virtual ICollection<ShiftMaster> ShiftMasters1 { get; set; }
        public virtual ICollection<SupportingStaffMember> SupportingStaffMembers { get; set; }
        public virtual ICollection<TaskSubDetail1> TaskSubDetail1 { get; set; }
        public virtual ICollection<TaskSubDetail2> TaskSubDetail2 { get; set; }
        public virtual ICollection<TaskTeam> TaskTeams { get; set; }
        public virtual ICollection<TaskTeamTaskTypeMapping> TaskTeamTaskTypeMappings { get; set; }
        public virtual ICollection<TaskTemplate> TaskTemplates { get; set; }
        public virtual ICollection<TaskType> TaskTypes { get; set; }
        public virtual ICollection<TaskTypeTaskSubDetail1Mapping> TaskTypeTaskSubDetail1Mapping { get; set; }
        public virtual ICollection<TaskTypeTaskSubDetail2Mapping> TaskTypeTaskSubDetail2Mapping { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<TempUserShift> TempUserShifts { get; set; }
        public virtual ICollection<TimeSheet> TimeSheets { get; set; }
        public virtual ICollection<TimesheetExcludedUser> TimesheetExcludedUsers { get; set; }
        public virtual ICollection<TimesheetExcludedUser> TimesheetExcludedUsers1 { get; set; }
        public virtual ICollection<TimesheetExcludedUser> TimesheetExcludedUsers2 { get; set; }
        public virtual ICollection<TimeSheetReportAccess> TimeSheetReportAccesses { get; set; }
        public virtual ICollection<TimeSheetReportAccess> TimeSheetReportAccesses1 { get; set; }
        public virtual ICollection<TrainingDetail> TrainingDetails { get; set; }
        public virtual ICollection<TrainingDetail> TrainingDetails1 { get; set; }
        public virtual ICollection<UserPromotionHistory> UserPromotionHistories { get; set; }
        public virtual ICollection<AssetDetailAttribute> AssetDetailAttributes { get; set; }
        public virtual ICollection<AssetDetailAttribute> AssetDetailAttributes1 { get; set; }
        public virtual ICollection<UserDetail> UserDetails { get; set; }
        public virtual ICollection<UserAccessCard> UserAccessCards { get; set; }
        public virtual ICollection<UserAchievement> UserAchievements { get; set; }
        public virtual ICollection<UserAchievementForMidYear> UserAchievementForMidYears { get; set; }
        public virtual ICollection<UserAchievementForMidYear> UserAchievementForMidYears1 { get; set; }
        public virtual ICollection<UserActivity> UserActivities { get; set; }
        public virtual ICollection<UserAddressDetail> UserAddressDetails { get; set; }
        public virtual ICollection<UserAddressDetail> UserAddressDetails1 { get; set; }
        public virtual ICollection<UserClientSideManagerAndProjectMapping> UserClientSideManagerAndProjectMappings { get; set; }
        public virtual ICollection<UserClientSideManagerAndProjectMapping> UserClientSideManagerAndProjectMappings1 { get; set; }
        public virtual ICollection<UserDetail> UserDetails1 { get; set; }
        public virtual ICollection<UserFamilyDetail> UserFamilyDetails { get; set; }
        public virtual ICollection<UserFamilyDetail> UserFamilyDetails1 { get; set; }
        public virtual ICollection<UserFeedback> UserFeedbacks { get; set; }
        public virtual ICollection<UserFeedback> UserFeedbacks1 { get; set; }
        public virtual ICollection<UserForm> UserForms { get; set; }
        public virtual ICollection<UserForm> UserForms1 { get; set; }
        public virtual ICollection<UserForm> UserForms2 { get; set; }
        public virtual ICollection<UserHierarchy> UserHierarchies { get; set; }
        public virtual ICollection<UserHierarchy> UserHierarchies1 { get; set; }
        public virtual ICollection<UserLocationHistory> UserLocationHistories { get; set; }
        public virtual ICollection<UsersHealthInsurance> UsersHealthInsurances { get; set; }
        public virtual ICollection<UserShiftMapping> UserShiftMappings { get; set; }
        public virtual ICollection<UserShiftMapping> UserShiftMappings1 { get; set; }
        public virtual ICollection<UserShiftMapping> UserShiftMappings2 { get; set; }
        public virtual ICollection<UserSkill> UserSkills { get; set; }
        public virtual ICollection<UsersOnshoreMgrMapping> UsersOnshoreMgrMappings { get; set; }
        public virtual ICollection<UsersToken> UsersTokens { get; set; }
        public virtual ICollection<UserTeamMapping> UserTeamMappings { get; set; }
        public virtual ICollection<Vertical> Verticals { get; set; }
        public virtual ICollection<API> APIs { get; set; }
        public virtual ICollection<APIUserPermission> APIUserPermissions { get; set; }
        public virtual ICollection<UserGoal> UserGoals { get; set; }
        public virtual ICollection<UserGoal> UserGoals1 { get; set; }
        public virtual ICollection<UserGoalHistory> UserGoalHistories { get; set; }
        public virtual ICollection<GoalCategory> GoalCategories { get; set; }
        public virtual ICollection<GoalCategory> GoalCategories1 { get; set; }
        public virtual ICollection<TeamGoal> TeamGoals { get; set; }
        public virtual ICollection<TeamGoalHistory> TeamGoalHistories { get; set; }
    }
}
