//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFeedback
    {
        public int FeedbackId { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsAcknowledged { get; set; }
        public Nullable<int> AcknowledgedBy { get; set; }
        public Nullable<System.DateTime> AcknowledgedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
