//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGoalComment
    {
        public long UserGoalCommentId { get; set; }
        public long UserGoalId { get; set; }
        public string SelfComment { get; set; }
        public string AppraiserComment { get; set; }
        public string ApproverComment { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual UserGoal UserGoal { get; set; }
    }
}
