//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SeatMaster
    {
        public int SeatId { get; set; }
        public int PremisesFloorId { get; set; }
        public string SeatNumber { get; set; }
        public int SeatTypeId { get; set; }
        public Nullable<int> BayNumber { get; set; }
        public int SeatStatusId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public bool IsChecked { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public string LocationName { get; set; }
        public string FloorName { get; set; }
        public string PremisesName { get; set; }
        public int LocationId { get; set; }
        public int PremisesId { get; set; }
        public int FloorId { get; set; }
        public Nullable<int> TotalBay { get; set; }
        public bool IsActive { get; set; }
        public string SeatTypeName { get; set; }
        public string StatusName { get; set; }
        public string UnitName { get; set; }
        public string UnitCode { get; set; }
    }
}
