//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwActiveUser
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public string EmployeeName { get; set; }
        public string DisplayName { get; set; }
        public int RoleId { get; set; }
        public string Role { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string Designation { get; set; }
        public bool IsIntern { get; set; }
        public int DesignationGroupId { get; set; }
        public string DesignationGroup { get; set; }
        public string EmailId { get; set; }
        public int RMId { get; set; }
        public string ReportingManagerName { get; set; }
        public string ReportingManagerEmailId { get; set; }
        public int GenderId { get; set; }
        public string Gender { get; set; }
        public string MobileNumber { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string BloodGroup { get; set; }
        public string ImagePath { get; set; }
        public string EmergencyContactNumber { get; set; }
        public bool IsImageVerified { get; set; }
        public Nullable<int> ProbationPeriodMonths { get; set; }
        public bool IsEligibleForLeave { get; set; }
        public Nullable<long> TeamId { get; set; }
        public string Team { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Department { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public string Division { get; set; }
    }
}
