//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmpAppraisalSetting
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string EmployeeName { get; set; }
        public int RoleId { get; set; }
        public bool IsActive { get; set; }
        public string EmailId { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> DateOfJoin { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string DesignationName { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> ReportTo { get; set; }
        public int AppraisalCycleId { get; set; }
        public Nullable<int> LastAppraisalCycleId { get; set; }
        public string AppraisalCycleName { get; set; }
        public string LastAppraisalCycleName { get; set; }
        public Nullable<System.DateTime> LastPromotionDate { get; set; }
        public long EmpAppraisalSettingId { get; set; }
        public int AppraisalSettingId { get; set; }
        public int AppraiserId { get; set; }
        public string AppraiserName { get; set; }
        public Nullable<int> AppraiserDesignation { get; set; }
        public int Approver1 { get; set; }
        public string Approver1Name { get; set; }
        public int Approver1Designation { get; set; }
        public Nullable<int> Approver2 { get; set; }
        public string Approver2Name { get; set; }
        public Nullable<int> Approver3 { get; set; }
        public string Approver3Name { get; set; }
        public Nullable<int> HRId { get; set; }
        public string HRName { get; set; }
        public int RMId { get; set; }
        public string RMName { get; set; }
        public Nullable<int> CompetencyFormId { get; set; }
        public int AppraisalStatusId { get; set; }
        public string FeedbackStatusName { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<int> LastPromotionDesignationId { get; set; }
        public string LastDesignationName { get; set; }
        public long TeamId { get; set; }
        public int TeamRoleId { get; set; }
        public string TeamName { get; set; }
        public int TeamHeadId { get; set; }
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public int DepartmentHeadId { get; set; }
        public int DivisionId { get; set; }
        public string DivisionName { get; set; }
        public int DivisionHeadId { get; set; }
        public int VerticalId { get; set; }
        public string VerticalName { get; set; }
        public int VerticalHeadId { get; set; }
        public int LocationId { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> AppraiserRecommendedForDesignationId { get; set; }
        public Nullable<int> AppraiserRecommendedPercentage { get; set; }
        public string AppraiserRecommendationComment { get; set; }
        public Nullable<int> Approver1RecommendedForDesignationId { get; set; }
        public Nullable<int> Approver1RecommendedPercentage { get; set; }
        public string Approver1RecommendationComment { get; set; }
        public Nullable<bool> AppraiserMarkedHighPotential { get; set; }
        public string AppraiserHighPotentialComment { get; set; }
        public Nullable<bool> Approver1MarkedHighPotential { get; set; }
        public string Approver1HighPotentialComment { get; set; }
        public Nullable<System.DateTime> SelfSubmitDate { get; set; }
        public Nullable<long> EmpAppraisalId { get; set; }
    }
}
