//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTimeSheetApprovedTasksForInternalReport
    {
        public System.DateTime Date { get; set; }
        public string Resource { get; set; }
        public string ResourceTeamName { get; set; }
        public string ProjectName { get; set; }
        public string Description { get; set; }
        public string TaskTeamName { get; set; }
        public string TaskType { get; set; }
        public string TaskSubDetail1 { get; set; }
        public string TaskSubDetail2 { get; set; }
        public decimal TimeSpent { get; set; }
    }
}
