//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUserDetail
    {
        public int UserId { get; set; }
        public int LocationId { get; set; }
        public string LocationName { get; set; }
        public int RoleId { get; set; }
        public bool IsActive { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string EmployeeName { get; set; }
        public string EmailId { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string DesignationName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> ReportTo { get; set; }
        public string RMName { get; set; }
        public string AppraiserName { get; set; }
        public Nullable<int> AppraisalCycleId { get; set; }
        public string AppraisalCycleName { get; set; }
        public long TeamId { get; set; }
        public int TeamRoleId { get; set; }
        public string TeamName { get; set; }
        public int TeamHeadId { get; set; }
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public int DepartmentHeadId { get; set; }
        public int DivisionId { get; set; }
        public string DivisionName { get; set; }
        public int DivisionHeadId { get; set; }
        public int VerticalId { get; set; }
        public string VerticalName { get; set; }
        public int VerticalHeadId { get; set; }
    }
}
